{{ if .Values.image.private }}
{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hydradevopsinfo.fullname" $root }}-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}