// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AbstraX.Generators.Pages.AboutPage
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using AbstraX.Generators;
    using AbstraX.Angular;
    using AbstraX;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\AboutPage\SassStyleSheetTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SassStyleSheetTemplate : AbstraX.Generators.Base.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"@import ""~@ionic/angular/css/typography.css"";

ion-toolbar {
  position: absolute;

  top: 0;
  left: 0;
  right: 0;

  --background: transparent;
  --color: white;
}

ion-toolbar ion-button,
ion-toolbar ion-back-button,
ion-toolbar ion-menu-button {
  --color: white;
}

ion-item {
  --min-height: 30px;
}

a.button {
  display: inline;
  color: inherit;
  text-decoration: none
}

img.button-logo {
  width: 18px;
  height: 18px;
  margin-top: 5px;
  margin-right: 10px;
}

div.list-panel {
  padding-left: 20px;
  padding-right: 20px;
}

.about-header {
  position: relative;

  width: 100%;
  height: 30%;
}

.about-header .about-image {
  position: absolute;

  top: 0;
  left: 0;
  bottom: 0;
  right: 0;

  background-position: center;
  background-size: cover;
  background-repeat: no-repeat;

  opacity: 1;

  transition: opacity 500ms ease-in-out;
}

.about-header {
  background-image: url(");
            
            #line 79 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\AboutPage\SassStyleSheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AboutImageUrl));
            
            #line default
            #line hidden
            this.Write(@");
  background-repeat:no-repeat;
  background-size: calc(100%);
  background-position: bottom;
}

@media only screen and (min-width: 992px) {
  .about-header {
    height: 40%;
  }
}

.about-info {
  position: absolute;
  width: 100%;
  margin-top: -10px;
  border-radius: 10px;
  background: var(--ion-background-color, #fff);
}

.about-info h3 {
  margin-top: 0;
}

.about-info ion-list {
  padding-top: 0;
}

.about-info p {
  line-height: 130%;

  color: var(--ion-color-dark);
}

.about-info ion-icon {
  margin-inline-end: 32px;
}

/*
 * iOS Only
 */

.ios .about-info {
  --ion-padding: 19px;
}

.ios .about-info h3 {
  font-weight: 700;
}
");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\AboutPage\SassStyleSheetTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private string _AboutImageUrlField;

/// <summary>
/// Access the AboutImageUrl parameter of the template.
/// </summary>
private string AboutImageUrl
{
    get
    {
        return this._AboutImageUrlField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool AboutImageUrlValueAcquired = false;
if (this.Session.ContainsKey("AboutImageUrl"))
{
    this._AboutImageUrlField = ((string)(this.Session["AboutImageUrl"]));
    AboutImageUrlValueAcquired = true;
}
if ((AboutImageUrlValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AboutImageUrl");
    if ((data != null))
    {
        this._AboutImageUrlField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
