# target:
#   type: queue
#   name: myQueue
template:
  name: vsbuild-template.yaml
  parameters:
    queue: myQueue
    projects: myProject.sln
    matrix:
      - buildConfiguration: debug
        buildPlatform: any cpu
      - buildConfiguration: release
        buildPlatform: any cpu
    variables:
      myCustomVar1: my value 1
      myCustomVar2: my value 2
  steps:
    preBuild:
      - task: credscan@1.*
