/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CarouselComponent {
        "containerClassName": string;
        "slideClassName": string;
        "slidecount": number;
    }
}
declare global {
    interface HTMLCarouselComponentElement extends Components.CarouselComponent, HTMLStencilElement {
    }
    var HTMLCarouselComponentElement: {
        prototype: HTMLCarouselComponentElement;
        new (): HTMLCarouselComponentElement;
    };
    interface HTMLElementTagNameMap {
        "carousel-component": HTMLCarouselComponentElement;
    }
}
declare namespace LocalJSX {
    interface CarouselComponent {
        "containerClassName"?: string;
        "slideClassName"?: string;
        "slidecount"?: number;
    }
    interface IntrinsicElements {
        "carousel-component": CarouselComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "carousel-component": LocalJSX.CarouselComponent & JSXBase.HTMLAttributes<HTMLCarouselComponentElement>;
        }
    }
}
