// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AbstraX.Generators.Server.WebAPIController
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using AbstraX.Generators;
    using AbstraX.Angular;
    using AbstraX.DataAnnotations;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class WebAPIIdentityControllerClassTemplate : AbstraX.Generators.Base.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 21 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

    var entityVariable = this.EntityName.ToCamelCase();
    var containerSetVariable = this.ContainerSet.ToCamelCase();
    var containerClass = this.Container.Name;
    var containerVariable = this.Container.Name.ToCamelCase();
    var lambdaParameter = containerVariable.Left(1);
    var userPasswordField = this.EntityProperties.GetIdentityField(IdentityFieldKind.PasswordHash);

            
            #line default
            #line hidden
            this.Write(@"using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;
using Utils;
using System.Security.Cryptography;
using System.Net.Mail;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using Microsoft.Data;
using System.Data;
using System.Security.Principal;
using ");
            
            #line 54 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".Services.Providers;\r\nusing ");
            
            #line 55 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".Services.Models;\r\nusing Models = ");
            
            #line 56 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".Entities.Models;\r\nusing ");
            
            #line 57 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 57 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".Services.Models.");
            
            #line 57 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 58 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".Entities.Models;\r\nusing ");
            
            #line 59 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".Entities;\r\n\r\nnamespace ");
            
            #line 61 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".Services.Controllers\r\n{\r\n    [Route(\"api/[controller]\")]\r\n    [ApiController]\r\n " +
                    "   public class ");
            
            #line 65 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write("Controller : ControllerBase\r\n    {\r\n        private ");
            
            #line 67 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerClass));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 67 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n        public ");
            
            #line 69 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ControllerName));
            
            #line default
            #line hidden
            this.Write("Controller(");
            
            #line 69 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerClass));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 69 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            this.");
            
            #line 71 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 71 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n");
            
            #line 74 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

    foreach (var relatedEntity in this.RelatedEntities)
    {
        var property = relatedEntity.Name;
        var propertyVariable = relatedEntity.Name.ToCamelCase();
        var sortBy = relatedEntity.SortBy;
        var sortDirection = relatedEntity.SortDirection;

        if (relatedEntity.IsEntitySet)
        {

            
            #line default
            #line hidden
            this.Write("        [HttpGet]\r\n        [Route(\"~/api/");
            
            #line 86 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyVariable));
            
            #line default
            #line hidden
            this.Write("\")]\r\n        [Authorize(Roles = \"Administrators\")]\r\n        public Models.Client");
            
            #line 88 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("[] Get");
            
            #line 88 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            var identity = this.User.Identity;\r\n\r\n            if (" +
                    "identity.IsAuthenticated)\r\n            {\r\n                var ");
            
            #line 94 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 94 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 94 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                return ");
            
            #line 96 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyVariable));
            
            #line default
            #line hidden
            this.Write(".Select(");
            
            #line 96 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => new ");
            
            #line 96 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n");
            
            #line 98 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            foreach (var entityProperty in this.EntityProperties)
            {

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 102 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 102 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 102 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 103 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            }

            if (sortDirection == SortDirection.Ascending)
            {

            
            #line default
            #line hidden
            this.Write("                }).OrderBy(c => c.");
            
            #line 109 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortBy));
            
            #line default
            #line hidden
            this.Write(").ToArray();\r\n");
            
            #line 110 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("                }).OrderByDescending(c => c.");
            
            #line 115 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortBy));
            
            #line default
            #line hidden
            this.Write(").ToArray();\r\n");
            
            #line 116 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("            }\r\n            else\r\n            {\r\n                throw new Unautho" +
                    "rizedAccessException();\r\n            }\r\n        }\r\n\r\n");
            
            #line 126 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

        }
        else
        {
            var parentRefName = relatedEntity.EntityParentRef.Name;
            var parentRefVariableName = parentRefName.ToCamelCase();
            var propertyRefVariableName = relatedEntity.ThisPropertyRef.Name.ToCamelCase();
            var scriptType = relatedEntity.ThisPropertyRefScriptType;
            var shortType = relatedEntity.ThisPropertyRefShortType;
            var containerSetName = relatedEntity.ContainerSet.Name;


            
            #line default
            #line hidden
            this.Write("        [Route(\"~/api/");
            
            #line 138 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetName));
            
            #line default
            #line hidden
            this.Write("/{");
            
            #line 138 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyRefVariableName));
            
            #line default
            #line hidden
            this.Write(":");
            
            #line 138 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(shortType.ToLower()));
            
            #line default
            #line hidden
            this.Write("}/");
            
            #line 138 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ToLower()));
            
            #line default
            #line hidden
            this.Write("\")]\r\n        [HttpGet]\r\n        public Models.");
            
            #line 140 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("[] Get");
            
            #line 140 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property));
            
            #line default
            #line hidden
            this.Write("For");
            
            #line 140 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 140 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(shortType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 140 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyRefVariableName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var identity = this.User.Identity;\r\n\r\n            if (i" +
                    "dentity.IsAuthenticated)\r\n            {\r\n                var ");
            
            #line 146 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 146 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 146 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                return ");
            
            #line 148 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyVariable));
            
            #line default
            #line hidden
            this.Write(".Where(");
            
            #line 148 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 148 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 148 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relatedEntity.ThisPropertyRef.Name));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 148 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyRefVariableName));
            
            #line default
            #line hidden
            this.Write(").Select(");
            
            #line 148 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => new ");
            
            #line 148 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n");
            
            #line 150 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            foreach (var entityProperty in this.EntityProperties)
            {

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 154 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 154 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 154 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 155 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            }

            if (sortDirection == SortDirection.Ascending)
            {

            
            #line default
            #line hidden
            this.Write("                }).OrderBy(");
            
            #line 161 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 161 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 161 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortBy));
            
            #line default
            #line hidden
            this.Write(").ToArray();\r\n");
            
            #line 162 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("                }).OrderByDescending(");
            
            #line 167 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 167 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 167 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortBy));
            
            #line default
            #line hidden
            this.Write(").ToArray();\r\n");
            
            #line 168 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("            }\r\n            else\r\n            {\r\n                throw new Unautho" +
                    "rizedAccessException();\r\n            }\r\n        }\r\n");
            
            #line 177 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n        [HttpGet]\r\n        [Route(\"~/api/");
            
            #line 183 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write("/{id:");
            
            #line 183 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.KeyType.ToLower()));
            
            #line default
            #line hidden
            this.Write("}\")]\r\n        public Models.Client");
            
            #line 184 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" Get");
            
            #line 184 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 184 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.KeyType));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            var identity = this.User.Identity;\r\n\r\n            if" +
                    " (identity.IsAuthenticated)\r\n            {\r\n                var ");
            
            #line 190 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 190 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 190 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ContainerSet));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                return ");
            
            #line 192 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(".Where(");
            
            #line 192 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 192 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 192 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.KeyName));
            
            #line default
            #line hidden
            this.Write(" == id).Select(");
            
            #line 192 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => new Models.Client");
            
            #line 192 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n");
            
            #line 194 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            foreach (var entityProperty in this.EntityProperties)
            {
                if (entityProperty != userPasswordField)
                {

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 200 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 200 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 200 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 201 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

                }
            }

            
            #line default
            #line hidden
            this.Write(@"                }).Single();
            }
            else
            {
                throw new UnauthorizedAccessException();
            }
        }

        [HttpPost]
        [Authorize(Roles = ""Administrator"")]
        public void Create");
            
            #line 215 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(Models.Client");
            
            #line 215 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 215 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var identity = this.User.Identity;\r\n\r\n            if (i" +
                    "dentity.IsAuthenticated)\r\n            {\r\n                var ");
            
            #line 221 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 221 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 221 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ContainerSet));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                ");
            
            #line 223 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(".Add(new Entities.");
            
            #line 223 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n");
            
            #line 225 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            foreach (var entityProperty in this.EntityProperties)
            {
                if (entityProperty.IsKey)
                {
                    if (entityProperty.DataType == "Guid")
                    {

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 233 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = Guid.NewGuid(),\r\n");
            
            #line 234 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

                    }
                }
                else
                {
                    if (entityProperty != userPasswordField)
                    {

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 242 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 242 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 242 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 243 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

                    }
                }
            }

            
            #line default
            #line hidden
            this.Write("                });\r\n\r\n                ");
            
            #line 250 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".SaveChanges();\r\n            }\r\n            else\r\n            {\r\n                " +
                    "throw new UnauthorizedAccessException();\r\n            }\r\n        }\r\n\r\n        /*" +
                    "\r\n        [HttpPost]\r\n        [Route(\"~/api/register\")]\r\n        public void Reg" +
                    "ister");
            
            #line 261 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(Models.Register");
            
            #line 261 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 261 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var ");
            
            #line 263 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 263 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 263 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ContainerSet));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n            ");
            
            #line 265 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(".Add(new Entities.");
            
            #line 265 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\r\n            {\r\n");
            
            #line 267 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            foreach (var entityProperty in this.EntityProperties)
            {
                if (entityProperty.IsKey)
                {
                    if (entityProperty.DataType == "Guid")
                    {

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 275 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = Guid.NewGuid(),\r\n");
            
            #line 276 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

                    }
                }
                else
                {

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 282 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 282 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 282 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 283 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

                }
            }

            
            #line default
            #line hidden
            this.Write("            });\r\n\r\n            ");
            
            #line 289 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".SaveChanges();\r\n        }\r\n        */\r\n\r\n        [HttpPut]\r\n        public void " +
                    "Update");
            
            #line 294 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(Models.Client");
            
            #line 294 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 294 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var identity = this.User.Identity;\r\n\r\n            if (i" +
                    "dentity.IsAuthenticated)\r\n            {\r\n                var update");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ContainerSet));
            
            #line default
            #line hidden
            this.Write(".Single(");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.KeyName));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 300 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.KeyName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 302 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

            foreach (var entityProperty in this.EntityProperties)
            {
                if (!entityProperty.IsKey && entityProperty != userPasswordField)
                {

            
            #line default
            #line hidden
            this.Write("                update");
            
            #line 308 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 308 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 308 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 308 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityProperty.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 309 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

                }
            }

            
            #line default
            #line hidden
            this.Write("\r\n                ");
            
            #line 314 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".SaveChanges();\r\n            }\r\n            else\r\n            {\r\n                " +
                    "throw new UnauthorizedAccessException();\r\n            }\r\n        }\r\n\r\n        [H" +
                    "ttpDelete]\r\n        public void Delete");
            
            #line 323 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 323 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.KeyType));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            var identity = this.User.Identity;\r\n\r\n            if" +
                    " (identity.IsAuthenticated)\r\n            {\r\n                var ");
            
            #line 329 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 329 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 329 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ContainerSet));
            
            #line default
            #line hidden
            this.Write(";\r\n                var delete");
            
            #line 330 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 330 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(".Single(");
            
            #line 330 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 330 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 330 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.KeyName));
            
            #line default
            #line hidden
            this.Write(" == id);\r\n\r\n                ");
            
            #line 332 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerSetVariable));
            
            #line default
            #line hidden
            this.Write(".Remove(delete");
            
            #line 332 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n                ");
            
            #line 334 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerVariable));
            
            #line default
            #line hidden
            this.Write(".SaveChanges();\r\n            }\r\n            else\r\n            {\r\n                " +
                    "throw new UnauthorizedAccessException();\r\n            }\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Server\WebAPIController\WebAPIIdentityControllerClassTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::System.Collections.Generic.List<RelatedEntity> _RelatedEntitiesField;

/// <summary>
/// Access the RelatedEntities parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<RelatedEntity> RelatedEntities
{
    get
    {
        return this._RelatedEntitiesField;
    }
}

private global::System.Collections.Generic.List<Generators.EntityProperty> _EntityPropertiesField;

/// <summary>
/// Access the EntityProperties parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<Generators.EntityProperty> EntityProperties
{
    get
    {
        return this._EntityPropertiesField;
    }
}

private string _RootNamespaceField;

/// <summary>
/// Access the RootNamespace parameter of the template.
/// </summary>
private string RootNamespace
{
    get
    {
        return this._RootNamespaceField;
    }
}

private string _ControllerNameField;

/// <summary>
/// Access the ControllerName parameter of the template.
/// </summary>
private string ControllerName
{
    get
    {
        return this._ControllerNameField;
    }
}

private string _EntityNameField;

/// <summary>
/// Access the EntityName parameter of the template.
/// </summary>
private string EntityName
{
    get
    {
        return this._EntityNameField;
    }
}

private string _KeyTypeField;

/// <summary>
/// Access the KeyType parameter of the template.
/// </summary>
private string KeyType
{
    get
    {
        return this._KeyTypeField;
    }
}

private string _KeyNameField;

/// <summary>
/// Access the KeyName parameter of the template.
/// </summary>
private string KeyName
{
    get
    {
        return this._KeyNameField;
    }
}

private string _ContainerSetField;

/// <summary>
/// Access the ContainerSet parameter of the template.
/// </summary>
private string ContainerSet
{
    get
    {
        return this._ContainerSetField;
    }
}

private global::AbstraX.ServerInterfaces.IElement _ContainerField;

/// <summary>
/// Access the Container parameter of the template.
/// </summary>
private global::AbstraX.ServerInterfaces.IElement Container
{
    get
    {
        return this._ContainerField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool RelatedEntitiesValueAcquired = false;
if (this.Session.ContainsKey("RelatedEntities"))
{
    this._RelatedEntitiesField = ((global::System.Collections.Generic.List<RelatedEntity>)(this.Session["RelatedEntities"]));
    RelatedEntitiesValueAcquired = true;
}
if ((RelatedEntitiesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RelatedEntities");
    if ((data != null))
    {
        this._RelatedEntitiesField = ((global::System.Collections.Generic.List<RelatedEntity>)(data));
    }
}
bool EntityPropertiesValueAcquired = false;
if (this.Session.ContainsKey("EntityProperties"))
{
    this._EntityPropertiesField = ((global::System.Collections.Generic.List<Generators.EntityProperty>)(this.Session["EntityProperties"]));
    EntityPropertiesValueAcquired = true;
}
if ((EntityPropertiesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityProperties");
    if ((data != null))
    {
        this._EntityPropertiesField = ((global::System.Collections.Generic.List<Generators.EntityProperty>)(data));
    }
}
bool RootNamespaceValueAcquired = false;
if (this.Session.ContainsKey("RootNamespace"))
{
    this._RootNamespaceField = ((string)(this.Session["RootNamespace"]));
    RootNamespaceValueAcquired = true;
}
if ((RootNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RootNamespace");
    if ((data != null))
    {
        this._RootNamespaceField = ((string)(data));
    }
}
bool ControllerNameValueAcquired = false;
if (this.Session.ContainsKey("ControllerName"))
{
    this._ControllerNameField = ((string)(this.Session["ControllerName"]));
    ControllerNameValueAcquired = true;
}
if ((ControllerNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ControllerName");
    if ((data != null))
    {
        this._ControllerNameField = ((string)(data));
    }
}
bool EntityNameValueAcquired = false;
if (this.Session.ContainsKey("EntityName"))
{
    this._EntityNameField = ((string)(this.Session["EntityName"]));
    EntityNameValueAcquired = true;
}
if ((EntityNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityName");
    if ((data != null))
    {
        this._EntityNameField = ((string)(data));
    }
}
bool KeyTypeValueAcquired = false;
if (this.Session.ContainsKey("KeyType"))
{
    this._KeyTypeField = ((string)(this.Session["KeyType"]));
    KeyTypeValueAcquired = true;
}
if ((KeyTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("KeyType");
    if ((data != null))
    {
        this._KeyTypeField = ((string)(data));
    }
}
bool KeyNameValueAcquired = false;
if (this.Session.ContainsKey("KeyName"))
{
    this._KeyNameField = ((string)(this.Session["KeyName"]));
    KeyNameValueAcquired = true;
}
if ((KeyNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("KeyName");
    if ((data != null))
    {
        this._KeyNameField = ((string)(data));
    }
}
bool ContainerSetValueAcquired = false;
if (this.Session.ContainsKey("ContainerSet"))
{
    this._ContainerSetField = ((string)(this.Session["ContainerSet"]));
    ContainerSetValueAcquired = true;
}
if ((ContainerSetValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ContainerSet");
    if ((data != null))
    {
        this._ContainerSetField = ((string)(data));
    }
}
bool ContainerValueAcquired = false;
if (this.Session.ContainsKey("Container"))
{
    this._ContainerField = ((global::AbstraX.ServerInterfaces.IElement)(this.Session["Container"]));
    ContainerValueAcquired = true;
}
if ((ContainerValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Container");
    if ((data != null))
    {
        this._ContainerField = ((global::AbstraX.ServerInterfaces.IElement)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
