pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'

resources:
  containers:
  - container: dotnetcore_arm
    image: huangtingluo/azure-pipelines-agent-eng:arm

  - container: dotnetcore_centos6
    image: huangtingluo/azure-pipelines-agent-eng:centos6

jobs:

################################################################################
- job: build_windows_x64_agent
################################################################################
  displayName: Windows Agent (x64)
  pool:
    vmImage: vs2017-win2016
  steps:

  # Steps template for windows platform
  - template: .vsts.template.windows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'Windows-x64'

  - script: dotnet tool install --global dotnet-reportgenerator-globaltool
    displayName: Install Report Generator

  - script: dev.cmd report
    displayName: Generate Code Coverage report
    workingDirectory: src

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: _reports/**/Cobertura.xml
      pathToSources: src

  # Package .NET Core Windows dependency (VC++ Redistributable)
  - template: .azure-pipelines/package-vcredist.yml
    parameters:
      layoutRoot: '_layout/win-x64'
      flavor: 'x64'
      condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Create agent package zip
  - script: dev.cmd package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Windows x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_windows_x86_agent
################################################################################
  displayName: Windows Agent (x86)
  pool:
    name: buildDevs
    demands: 'Agent.OSArchitecture -equals X86'
  steps:

  # Steps template for windows platform
  - template: .vsts.template.windows.yml
    parameters:
      testLogTitle: 'Windows-x86'

  # Package .NET Core Windows dependency (VC++ Redistributable)
  - template: .azure-pipelines/package-vcredist.yml
    parameters:
      layoutRoot: '_layout/win-x86'
      flavor: 'x86'
      condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Create agent package zip
  - script: dev.cmd package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Windows x86)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_linux_x64_agent
################################################################################
  displayName: Linux Agent (x64)
  pool:
    vmImage: ubuntu-16.04
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'Linux-x64'
      enableADOLogIssue: 'true'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Linux x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_linux_arm_agent
################################################################################
  displayName: Linux Agent (ARM)
  pool:
    name: buildDevs
    demands: 'Agent.OSArchitecture -equals ARM'
  container: dotnetcore_arm
  timeoutInMinutes: 75
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      testLogTitle: 'Linux-ARM'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Linux ARM)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_rhel6_x64_agent
################################################################################
  displayName: RHEL6 Agent (x64)
  pool:
    vmImage: ubuntu-16.04
  container: dotnetcore_centos6
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      testLogTitle: 'RHEL-x64'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (RHEL6 x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_osx_agent
################################################################################
  displayName: macOS Agent (x64)
  pool:
    vmImage: macOS-10.13
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'macOS-x64'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (OSX)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container
