// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AbstraX.Generators.Pages.NavigationGridPage
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using AbstraX.Generators;
    using AbstraX.Angular;
    using AbstraX.DataAnnotations;
    using AbstraX;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class NavigationGridClassTemplate : AbstraX.Generators.Base.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 27 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 
    var pageName = this.PageName.ToCamelCase();
    var modelVariable = this.EntityName.ToCamelCase();
    var className = this.PageName + "Page";
    var textIdentifier = this.GridColumns.GetTextIdentifier();
    var textIdentifierName = textIdentifier.Name;
    var gridName = this.PageName.ToCamelCase() + "Grid"; 
    string parentRefVariable = null;
    string propertyRefName = null;

    if (this.EntityPropertyRefName != null)
    {
        propertyRefName = this.EntityPropertyRefName.ToCamelCase();
    }

    if (this.EntityParentRefName != null)
    {
        parentRefVariable = this.EntityParentRefName.ToCamelCase();
    }

    if (this.IsComponent)
    {
        var component = new Component(className, this.UIKind);

        this.Declarations.Add(component);
        this.Exports.Add(component);
    }
    else
    {
        var page = new Page(className, this.UIKind);

        this.Declarations.Add(page);
        this.Exports.Add(page);
    }

    foreach (var import in this.Imports)
    {
        this.WriteLine(import.DeclarationCode);
    }

            
            #line default
            #line hidden
            this.Write("\r\n@PageName(\"");
            
            #line 68 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("\")\r\n@RecordExpression(\"");
            
            #line 69 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(" [{");
            
            #line 69 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MakeVariable(modelVariable, textIdentifierName)));
            
            #line default
            #line hidden
            this.Write("}]\")\r\n");
            
            #line 70 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 if (!IsComponent)
   {

            
            #line default
            #line hidden
            this.Write("@IonicPage()\r\n");
            
            #line 74 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

   }

            
            #line default
            #line hidden
            
            #line 77 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 if (this.Authorize.Length > 0)
   {

            
            #line default
            #line hidden
            this.Write("@Authorize(\"");
            
            #line 80 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Authorize));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 81 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 
   }

            
            #line default
            #line hidden
            this.Write("@Component({\r\n  selector: \'page-");
            
            #line 85 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageName));
            
            #line default
            #line hidden
            this.Write("\',\r\n  templateUrl: \'");
            
            #line 86 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageName));
            
            #line default
            #line hidden
            this.Write(".html\',\r\n  styleUrls: [\'./");
            
            #line 87 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageName));
            
            #line default
            #line hidden
            this.Write(".scss\']\r\n})\r\nexport class ");
            
            #line 89 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" extends GridPage {\r\n");
            
            #line 90 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 
    if (this.EntityParentRefName != null) 
    {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 94 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 94 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityParentRefName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 95 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n  columnDefs = [];\r\n  rowData: any;\r\n  @ViewChild(\"");
            
            #line 101 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write("\") ");
            
            #line 101 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write(": AgGridNg2;\r\n\r\n  constructor(public navCtrl: NavController,\r\n    public navParam" +
                    "s: NavParams,\r\n    public ");
            
            #line 105 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider: ");
            
            #line 105 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Provider,\r\n    public ");
            
            #line 106 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Validator: ");
            
            #line 106 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(@"Validator,
    public toastCtrl: ToastController,
    public popoverCtrl: PopoverController,
    private alertCtrl: AlertController,
    private translateService: TranslateService,
    private ngZone: NgZone) {

    super();

    this.translateService.get([");
            
            #line 115 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 

    var builder = new StringBuilder();

    foreach (var column in this.GridColumns)
    {
        builder.AppendWithLeadingIfLength(", ", column.TranslationKey.SurroundWithQuotes());
    }

    this.Write(builder.ToString());

    
            
            #line default
            #line hidden
            this.Write("]).subscribe(values => {\r\n        this.columnDefs = \r\n        [\r\n");
            
            #line 129 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    foreach (var column in this.GridColumns)
    {

            
            #line default
            #line hidden
            this.Write("          { headerName: ");
            
            #line 133 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("values[\"{0}\"]", column.TranslationKey)));
            
            #line default
            #line hidden
            this.Write(", field: \"");
            
            #line 133 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\", editable: true },\r\n");
            
            #line 134 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    }

    foreach (var managedList in this.ManagedLists)
    {

            
            #line default
            #line hidden
            this.Write("          { headerName: ");
            
            #line 140 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("values[\"{0}\"]", managedList.TranslationKey)));
            
            #line default
            #line hidden
            this.Write(", field: \"");
            
            #line 140 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Data\", cellRenderer: this.render");
            
            #line 140 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write(" },\r\n          {\r\n             headerName: \"\", field: \"");
            
            #line 142 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Id\", cellRendererFramework: EditDeleteButtons, width: 80, cellRendererParams: {\r\n" +
                    "                 onEditClick: (rowData) => this.onEdit");
            
            #line 143 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Click(rowData),\r\n                 onDeleteClick: (rowData) => this.onDelete");
            
            #line 144 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Click(rowData)\r\n              }\r\n            }\r\n");
            
            #line 147 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        ];\r\n    });\r\n  }\r\n\r\n  ngOnInit() {\r\n\r\n");
            
            #line 156 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 
    if (this.EntityParentRefName != null) 
    {

            
            #line default
            #line hidden
            this.Write("    this.");
            
            #line 160 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefVariable));
            
            #line default
            #line hidden
            this.Write(" = <");
            
            #line 160 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityParentRefName));
            
            #line default
            #line hidden
            this.Write(">this.navParams.get(\"");
            
            #line 160 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefVariable));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 161 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

        if (this.CustomQueries.HasQueryForKind(QueryKind.LoadParentReference))
        {
            var query = this.CustomQueries.GetQueryForKind(QueryKind.LoadParentReference);

            
            #line default
            #line hidden
            this.Write("    this.");
            
            #line 166 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write(".cellValueChanged.subscribe(p => this.cellValueChanged(p));\r\n\r\n    if (this.");
            
            #line 168 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefVariable));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n    {\r\n      let observable = this.");
            
            #line 170 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider.");
            
            #line 170 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.ClientProviderMethodName));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n      observable.subscribe((response) => {\r\n        this.");
            
            #line 173 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefVariable));
            
            #line default
            #line hidden
            this.Write(" = <");
            
            #line 173 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityParentRefName));
            
            #line default
            #line hidden
            this.Write(">response;\r\n        this.update");
            
            #line 174 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("Grid();\r\n      }, err => {\r\n        let toast = this.toastCtrl.create({\r\n        " +
                    "  message: err.message,\r\n          duration: 3000,\r\n          position: \"top\"\r\n " +
                    "       });\r\n        toast.present();\r\n      });\r\n    }\r\n    else\r\n    {\r\n       " +
                    " this.");
            
            #line 186 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write(".cellValueChanged.subscribe(p => this.cellValueChanged(p));\r\n        this.update");
            
            #line 187 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("Grid();\r\n    }\r\n");
            
            #line 189 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("\r\n    this.update");
            
            #line 195 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("Grid();\r\n");
            
            #line 196 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

        }
    }

    foreach (var managedList in this.ManagedLists)
    {

            
            #line default
            #line hidden
            this.Write("    this.bindClickMethod(\"");
            
            #line 203 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\", \"on");
            
            #line 203 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("Click\", this.on");
            
            #line 203 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("Click);\r\n");
            
            #line 204 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  }\r\n\r\n  ionViewDidLoad() {\r\n    console.log(\"ionViewDidLoad ");
            
            #line 210 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("\");\r\n  }\r\n\r\n  cellValueChanged(params: any) {");
            
            #line 213 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    builder = new StringBuilder();

    foreach (var column in this.GridColumns)
    {
        builder.AppendWithLeadingIfLength(", ", modelVariable + "." + this.MakeVariable(modelVariable, column.Name));
    }

            
            #line default
            #line hidden
            this.Write("\r\n    let ");
            
            #line 222 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(" = <");
            
            #line 222 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(">params.data;\r\n    let ");
            
            #line 223 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form = this.");
            
            #line 223 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Validator.create");
            
            #line 223 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Form(");
            
            #line 223 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(builder.ToString()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n    if (");
            
            #line 225 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form.invalid) {\r\n      let column = params.column;\r\n      let columnName = column" +
                    ".colId;\r\n      let control = this.");
            
            #line 228 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Validator.getControl(columnName);\r\n      let rowNode = params.node;\r\n      let to" +
                    "ast: Toast;\r\n\r\n      rowNode.setDataValue(column, params.oldValue);\r\n\r\n      thi" +
                    "s.");
            
            #line 234 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write(".api.stopEditing(true);\r\n      this.");
            
            #line 235 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write(".api.setFocusedCell(params.rowIndex, columnName);\r\n      this.");
            
            #line 236 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write(".api.startEditingCell({ rowIndex: params.rowIndex, colKey: columnName });\r\n\r\n    " +
                    "  toast = this.toastCtrl.create({\r\n        message: this.");
            
            #line 239 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Validator.getValidationErrorsText(columnName),\r\n        duration: 2000,\r\n        " +
                    "position: \"top\"\r\n      });\r\n\r\n      toast.present().then((result) => {\r\n\r\n      " +
                    "  let editor = new List<ICellEditorComp>(this.");
            
            #line 246 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridName));
            
            #line default
            #line hidden
            this.Write(".api.getCellEditorInstances()).single();\r\n        let input = <HTMLInputElement>e" +
                    "ditor.getGui();\r\n\r\n        input.focus();\r\n\r\n      }, (err) => {\r\n        consol" +
                    "e.log(err);\r\n      });\r\n    }\r\n  }\r\n\r\n  update");
            
            #line 257 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("Grid() {\r\n");
            
            #line 258 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
 
    if (this.EntityParentRefName != null) 
    {

            
            #line default
            #line hidden
            this.Write("    this.rowData = this.");
            
            #line 262 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider.get");
            
            #line 262 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ParentEntityName));
            
            #line default
            #line hidden
            this.Write("For");
            
            #line 262 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityParentRefName));
            
            #line default
            #line hidden
            this.Write("(this.");
            
            #line 262 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 262 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyRefName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 263 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("    this.rowData = this.");
            
            #line 268 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider.get");
            
            #line 268 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ParentEntityName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 269 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  }\r\n\r\n  presentAdd");
            
            #line 274 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("() {\r\n\r\n    let popover = this.popoverCtrl.create(Edit");
            
            #line 276 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Page, { userAction: \"New ");
            
            #line 276 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\" });\r\n    popover.present();\r\n\r\n    popover.onDidDismiss((data: any, role: strin" +
                    "g) => {\r\n      this.update");
            
            #line 280 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("Grid();\r\n    });\r\n  }\r\n\r\n  onEdit");
            
            #line 284 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Click(params: any) {\r\n    this.ngZone.run(() => this.edit");
            
            #line 285 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(<");
            
            #line 285 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(">params));\r\n  }\r\n\r\n  onDelete");
            
            #line 288 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Click(params: any) {\r\n    this.ngZone.run(() => this.delete");
            
            #line 289 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(<");
            
            #line 289 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(">params));\r\n  }\r\n\r\n  edit");
            
            #line 292 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 292 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 292 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(") {\r\n\r\n    let popover = this.popoverCtrl.create(Edit");
            
            #line 294 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Page, { userAction: \"Edit ");
            
            #line 294 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 294 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 294 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(" });\r\n    popover.present();\r\n\r\n    popover.onDidDismiss((data: any, role: string" +
                    ") => {\r\n      this.update");
            
            #line 298 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("Grid();\r\n    });\r\n  }\r\n\r\n");
            
            #line 302 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    // todo kn - translate below text
    // see https://damienbod.com/2014/03/20/web-api-localization/

            
            #line default
            #line hidden
            this.Write("  delete");
            
            #line 306 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 306 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 306 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(") {\r\n\r\n    this.presentConfirm(() => {\r\n      let observable = this.");
            
            #line 309 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider.delete");
            
            #line 309 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 309 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 309 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Id);\r\n\r\n      observable.subscribe((response) => {\r\n        this.update");
            
            #line 312 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write(@"Grid();
      }, err => {
        let toast = this.toastCtrl.create({
          message: err.message,
          duration: 3000,
          position: ""top""
        });
        toast.present();
      });

    });
  }

  presentConfirm(handler: Function) {
    let alert = this.alertCtrl.create({
      title: ""Confirm delete"",
      message: ""Are you sure you want to delete this ");
            
            #line 328 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(@"?"",
      buttons: [
        {
          text: ""Cancel"",
          role: ""cancel"",
          handler: () => {
            console.log(""Cancel clicked"");
          }
        },
        {
          text: ""Delete"",
          handler: () => {
            handler();
          }
        }
      ]
    });

    alert.present();
  }
");
            
            #line 348 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    foreach (var managedList in this.ManagedLists)
    {

            
            #line default
            #line hidden
            this.Write("\r\n  render");
            
            #line 353 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("(params: any): string {\r\n    return GridPage.renderLinkElement(\"");
            
            #line 354 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PageName));
            
            #line default
            #line hidden
            this.Write("\", \"on");
            
            #line 354 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("Click\", \"Manage ");
            
            #line 354 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("\", params);\r\n  }\r\n\r\n  on");
            
            #line 357 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("Click(params: string) {\r\n    this.ngZone.run(() => this.manage");
            
            #line 358 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("(params));\r\n  }\r\n\r\n  manage");
            
            #line 361 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("(params) {\r\n\r\n    var obj = this.parseLinkParams(params);\r\n    this.navCtrl.push(" +
                    "");
            
            #line 364 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(managedList.Name));
            
            #line default
            #line hidden
            this.Write("Page, obj);\r\n  }\r\n");
            
            #line 366 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\CloudIDEaaS\develop\ApplicationGenerator.IonicAngular\Generators\Pages\NavigationGridPage\NavigationGridClassTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::System.Collections.Generic.List<ManagedList> _ManagedListsField;

/// <summary>
/// Access the ManagedLists parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<ManagedList> ManagedLists
{
    get
    {
        return this._ManagedListsField;
    }
}

private global::System.Collections.Generic.List<GridColumn> _GridColumnsField;

/// <summary>
/// Access the GridColumns parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<GridColumn> GridColumns
{
    get
    {
        return this._GridColumnsField;
    }
}

private global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration> _ImportsField;

/// <summary>
/// Access the Imports parameter of the template.
/// </summary>
private global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration> Imports
{
    get
    {
        return this._ImportsField;
    }
}

private global::System.Collections.Generic.List<ESModule> _ExportsField;

/// <summary>
/// Access the Exports parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<ESModule> Exports
{
    get
    {
        return this._ExportsField;
    }
}

private global::System.Collections.Generic.List<IDeclarable> _DeclarationsField;

/// <summary>
/// Access the Declarations parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<IDeclarable> Declarations
{
    get
    {
        return this._DeclarationsField;
    }
}

private global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo> _CustomQueriesField;

/// <summary>
/// Access the CustomQueries parameter of the template.
/// </summary>
private global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo> CustomQueries
{
    get
    {
        return this._CustomQueriesField;
    }
}

private string _PageNameField;

/// <summary>
/// Access the PageName parameter of the template.
/// </summary>
private string PageName
{
    get
    {
        return this._PageNameField;
    }
}

private string _AuthorizeField;

/// <summary>
/// Access the Authorize parameter of the template.
/// </summary>
private string Authorize
{
    get
    {
        return this._AuthorizeField;
    }
}

private string _EntityNameField;

/// <summary>
/// Access the EntityName parameter of the template.
/// </summary>
private string EntityName
{
    get
    {
        return this._EntityNameField;
    }
}

private string _ParentEntityNameField;

/// <summary>
/// Access the ParentEntityName parameter of the template.
/// </summary>
private string ParentEntityName
{
    get
    {
        return this._ParentEntityNameField;
    }
}

private string _EntityParentRefNameField;

/// <summary>
/// Access the EntityParentRefName parameter of the template.
/// </summary>
private string EntityParentRefName
{
    get
    {
        return this._EntityParentRefNameField;
    }
}

private string _EntityPropertyRefNameField;

/// <summary>
/// Access the EntityPropertyRefName parameter of the template.
/// </summary>
private string EntityPropertyRefName
{
    get
    {
        return this._EntityPropertyRefNameField;
    }
}

private bool _IsComponentField;

/// <summary>
/// Access the IsComponent parameter of the template.
/// </summary>
private bool IsComponent
{
    get
    {
        return this._IsComponentField;
    }
}

private global::AbstraX.DataAnnotations.UIKind _UIKindField;

/// <summary>
/// Access the UIKind parameter of the template.
/// </summary>
private global::AbstraX.DataAnnotations.UIKind UIKind
{
    get
    {
        return this._UIKindField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool ManagedListsValueAcquired = false;
if (this.Session.ContainsKey("ManagedLists"))
{
    this._ManagedListsField = ((global::System.Collections.Generic.List<ManagedList>)(this.Session["ManagedLists"]));
    ManagedListsValueAcquired = true;
}
if ((ManagedListsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ManagedLists");
    if ((data != null))
    {
        this._ManagedListsField = ((global::System.Collections.Generic.List<ManagedList>)(data));
    }
}
bool GridColumnsValueAcquired = false;
if (this.Session.ContainsKey("GridColumns"))
{
    this._GridColumnsField = ((global::System.Collections.Generic.List<GridColumn>)(this.Session["GridColumns"]));
    GridColumnsValueAcquired = true;
}
if ((GridColumnsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GridColumns");
    if ((data != null))
    {
        this._GridColumnsField = ((global::System.Collections.Generic.List<GridColumn>)(data));
    }
}
bool ImportsValueAcquired = false;
if (this.Session.ContainsKey("Imports"))
{
    this._ImportsField = ((global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration>)(this.Session["Imports"]));
    ImportsValueAcquired = true;
}
if ((ImportsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Imports");
    if ((data != null))
    {
        this._ImportsField = ((global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration>)(data));
    }
}
bool ExportsValueAcquired = false;
if (this.Session.ContainsKey("Exports"))
{
    this._ExportsField = ((global::System.Collections.Generic.List<ESModule>)(this.Session["Exports"]));
    ExportsValueAcquired = true;
}
if ((ExportsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Exports");
    if ((data != null))
    {
        this._ExportsField = ((global::System.Collections.Generic.List<ESModule>)(data));
    }
}
bool DeclarationsValueAcquired = false;
if (this.Session.ContainsKey("Declarations"))
{
    this._DeclarationsField = ((global::System.Collections.Generic.List<IDeclarable>)(this.Session["Declarations"]));
    DeclarationsValueAcquired = true;
}
if ((DeclarationsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Declarations");
    if ((data != null))
    {
        this._DeclarationsField = ((global::System.Collections.Generic.List<IDeclarable>)(data));
    }
}
bool CustomQueriesValueAcquired = false;
if (this.Session.ContainsKey("CustomQueries"))
{
    this._CustomQueriesField = ((global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo>)(this.Session["CustomQueries"]));
    CustomQueriesValueAcquired = true;
}
if ((CustomQueriesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("CustomQueries");
    if ((data != null))
    {
        this._CustomQueriesField = ((global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo>)(data));
    }
}
bool PageNameValueAcquired = false;
if (this.Session.ContainsKey("PageName"))
{
    this._PageNameField = ((string)(this.Session["PageName"]));
    PageNameValueAcquired = true;
}
if ((PageNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("PageName");
    if ((data != null))
    {
        this._PageNameField = ((string)(data));
    }
}
bool AuthorizeValueAcquired = false;
if (this.Session.ContainsKey("Authorize"))
{
    this._AuthorizeField = ((string)(this.Session["Authorize"]));
    AuthorizeValueAcquired = true;
}
if ((AuthorizeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Authorize");
    if ((data != null))
    {
        this._AuthorizeField = ((string)(data));
    }
}
bool EntityNameValueAcquired = false;
if (this.Session.ContainsKey("EntityName"))
{
    this._EntityNameField = ((string)(this.Session["EntityName"]));
    EntityNameValueAcquired = true;
}
if ((EntityNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityName");
    if ((data != null))
    {
        this._EntityNameField = ((string)(data));
    }
}
bool ParentEntityNameValueAcquired = false;
if (this.Session.ContainsKey("ParentEntityName"))
{
    this._ParentEntityNameField = ((string)(this.Session["ParentEntityName"]));
    ParentEntityNameValueAcquired = true;
}
if ((ParentEntityNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ParentEntityName");
    if ((data != null))
    {
        this._ParentEntityNameField = ((string)(data));
    }
}
bool EntityParentRefNameValueAcquired = false;
if (this.Session.ContainsKey("EntityParentRefName"))
{
    this._EntityParentRefNameField = ((string)(this.Session["EntityParentRefName"]));
    EntityParentRefNameValueAcquired = true;
}
if ((EntityParentRefNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityParentRefName");
    if ((data != null))
    {
        this._EntityParentRefNameField = ((string)(data));
    }
}
bool EntityPropertyRefNameValueAcquired = false;
if (this.Session.ContainsKey("EntityPropertyRefName"))
{
    this._EntityPropertyRefNameField = ((string)(this.Session["EntityPropertyRefName"]));
    EntityPropertyRefNameValueAcquired = true;
}
if ((EntityPropertyRefNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityPropertyRefName");
    if ((data != null))
    {
        this._EntityPropertyRefNameField = ((string)(data));
    }
}
bool IsComponentValueAcquired = false;
if (this.Session.ContainsKey("IsComponent"))
{
    this._IsComponentField = ((bool)(this.Session["IsComponent"]));
    IsComponentValueAcquired = true;
}
if ((IsComponentValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("IsComponent");
    if ((data != null))
    {
        this._IsComponentField = ((bool)(data));
    }
}
bool UIKindValueAcquired = false;
if (this.Session.ContainsKey("UIKind"))
{
    this._UIKindField = ((global::AbstraX.DataAnnotations.UIKind)(this.Session["UIKind"]));
    UIKindValueAcquired = true;
}
if ((UIKindValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("UIKind");
    if ((data != null))
    {
        this._UIKindField = ((global::AbstraX.DataAnnotations.UIKind)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
