// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AbstraX.Generators.Client.Theme
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using AbstraX;
    using AbstraX.Generators;
    using AbstraX.Angular;
    using AbstraX.Resources;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DataJsonTemplate : AbstraX.Generators.Base.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("{\r\n  \"welcome\":\r\n  [\r\n    {\r\n      \"page\":\r\n      {\r\n        \"pageTitle\": \"");
            
            #line 21 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"metaDescription\": \"\",\r\n        \"metaKeywords\": \"\"\r\n      },\r\n      \"" +
                    "details\":\r\n      {\r\n        \"welcomeTitle\": \"Welcome to ");
            
            #line 27 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"description\": \"");
            
            #line 28 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppDescription.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"startAppUrlTitle\": \"Skip this intro and start utilizing the ");
            
            #line 29 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write(" right away\",\r\n        \"splashScreenAlt\": \"Splash screen for  ");
            
            #line 30 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\"\r\n      }\r\n    }\r\n  ],\r\n  \"about\":\r\n  [\r\n    {\r\n      \"page\":\r\n      {\r\n        " +
                    "\"pageTitle\": \"About the ");
            
            #line 39 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"metaDescription\": \"\",\r\n        \"metaKeywords\": \"\"\r\n      },\r\n      \"" +
                    "details\":\r\n      {\r\n        \"header\":\r\n        {\r\n          \"aboutBannerAlt\": \"B" +
                    "anner for the ");
            
            #line 47 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"description\": \"");
            
            #line 48 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppDescription.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n          \"version\": \"$version\"\r\n        },\r\n");
            
            #line 51 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

    if (this.MarketingObjectProperties != null)
    {
        var other = this.MarketingObjectProperties.Other;
        var rateUs = this.MarketingObjectProperties.RateUs;
        var otherLinks = this.MarketingObjectProperties.OtherLinks;
        SocialMediaEntry[] socialMedia = null;
        AppStoreEntry[] appStores = null;

        if (this.MarketingObjectProperties.SocialMedia != null)
        {
            socialMedia = this.MarketingObjectProperties.SocialMedia.SocialMedia;
        }

        if (this.MarketingObjectProperties.RateUs != null)
        {
            appStores = this.MarketingObjectProperties.RateUs.AppStores;
        }


            
            #line default
            #line hidden
            this.Write("        \"mainPageLinks\":\r\n        [\r\n");
            
            #line 73 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

        if (other != null)
        {
            if (other.AdvertisingLink != null)
            {
                var linkProperties = this.MarketingObjectProperties.GetLinkProperties("AdvertisingLink", other.AdvertisingLink);

            
            #line default
            #line hidden
            this.Write("              \r\n            {\r\n                \"title\": \"");
            
            #line 81 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"text\": \"");
            
            #line 82 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"url\": \"");
            
            #line 83 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(other.AdvertisingLink));
            
            #line default
            #line hidden
            this.Write("\"\r\n            },\r\n");
            
            #line 85 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

            }

            if (other.ConnectWithUsLink != null)
            {
                var linkProperties = this.MarketingObjectProperties.GetLinkProperties("ConnectWithUsLink", other.ConnectWithUsLink);

            
            #line default
            #line hidden
            this.Write("            {\r\n                \"title\": \"");
            
            #line 93 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"text\": \"");
            
            #line 94 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"url\": \"");
            
            #line 95 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(other.ConnectWithUsLink));
            
            #line default
            #line hidden
            this.Write("\"\r\n            }\r\n");
            
            #line 97 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

            }

        }

            
            #line default
            #line hidden
            this.Write("        ],\r\n        \"socialLinks\":\r\n        [\r\n");
            
            #line 105 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

        if (other != null)
        {
            if (other.EmailUsLink != null)
            {
                var linkProperties = this.MarketingObjectProperties.GetLinkProperties("EmailUsLink", other.EmailUsLink);

            
            #line default
            #line hidden
            this.Write("              \r\n            {\r\n                \"visitTitle\": \"");
            
            #line 113 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"visitText\": \"");
            
            #line 114 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"tinyLogo\": \"data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAA" +
                    "wAAAAMCAIAAADZF8uwAAAAK3RFWHRDcmVhdGlvbiBUaW1lAFN1biA3IE1hciAyMDIxIDE2OjQ4OjQ4IC" +
                    "0wNjAw6ip09QAAAAd0SU1FB+UDEBITBOTE/0sAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAEZ0FNQQAAsY" +
                    "8L/GEFAAAAjklEQVR42mNgoCa4eOni1WtXsKLLly9BFTk5OT199uTf/79o6MWL525ublBF+/bt1dfX37" +
                    "t3D7KK/Qf2GxoaAqWgioBCQJMcHR2bm5v//vsDRK2tLU5OjhDjEYqA6Nfvn6VlpZ5enl5enkAGkAsRR1" +
                    "EERP///9uwYf2GjeuBDLgguiKsCKoIl/8hiKqhDQD+98Z2zQCS9QAAAABJRU5ErkJggg==\",\r\n      " +
                    "          \"smallLogo\": \"data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCA" +
                    "MAAABEpIrGAAAAB3RJTUUH5QMVEycZCvT6YAAAAAlwSFlzAAAewQAAHsEBw2lUUwAAAARnQU1BAACxjw" +
                    "v8YQUAAAB+UExURQD/AG9vb9fX1xgYGAAAAJSUlLy8vHd3d8XFxRQUFCQkJB8fH62trV1dXYKCgsTExG" +
                    "VlZRwcHE9PT93d3SUlJXx8fD4+PkFBQd/f3zExMU5OTtnZ2eDg4PX19TMzM/T09EdHR/j4+DAwMPLy8n" +
                    "19ffDw8EZGRktLS15eXvf390EMpAcAAAABdFJOUwBA5thmAAAAzUlEQVR42uWSzRaCIBCFRwIDG62kUt" +
                    "PK7P/9XzAINRVs1Tktmo2DfHfuMADwH8Eq+iGuOeBhHBFsx4AKhYgROckoqORGirtL/oiUEF75+eJXtj" +
                    "zRXzDLAE89H+1u1tD82pIibPdLSTZ1Cm9RdKx9BOu03QEQzXnKlMiY2gCi8skLROW+l4kF6H1VZs25dk" +
                    "/SbAAw7A8rlqsewPzhMBdk2QGiuT1sj4sWmHLXZZiqGvDIxHlZDA0QkBl1B4YacNc3s1N9wFj9po9fv/" +
                    "jvxBOhNA+9p30rowAAAABJRU5ErkJggg==\",\r\n                \"largeLogo\": \"data:image/g" +
                    "if;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAMAAAC7IEhfAAAAK3RFWHRDcmVhdGlvbiBUaW" +
                    "1lAFN1biA3IE1hciAyMDIxIDE2OjEwOjA2IC0wNjAwXN/t5AAAAAd0SU1FB+UDEBIMEURDFT4AAAAJcE" +
                    "hZcwAACxIAAAsSAdLdfvwAAAAEZ0FNQQAAsY8L/GEFAAAB0VBMVEUA/wC/v7+AgIBJSUklJSUGBgYBAQ" +
                    "EDAwMhISFDQ0N4eHi1tbV0dHQeHh4CAgIYGBhoaGhra2sMDAwAAAAHBwdaWlqqqqoWFhYUFBSSkpJvb2" +
                    "8FBQVXV1dTU1M/Pz9YWFgEBARAQECzs7OXl5ciIiIgICA9PT0+Pj43NzcTExN+fn4wMDDy8vL9/f3+/v" +
                    "78/Pybm5tdXV0SEhJsbGz09PT////19fX7+/vX19eMjIxtbW3b29vg4OD4+PhQUFCjo6Pa2toxMTGPj4" +
                    "/n5+f5+flmZmZRUVEZGRmHh4fq6upycnJCQkK6urp3d3c8PDzu7u42Njbs7Ox7e3tpaWlxcXFBQUHx8f" +
                    "GampotLS3i4uL6+vpnZ2dLS0uvr68kJCQjIyMoKCj39/eEhIQ1NTXAwMDOzs5UVFRcXFyxsbEmJiYKCg" +
                    "pzc3Pw8PDMzMzz8/NWVlYLCwu3t7cnJyfPz8/t7e1kZGSysrIpKSmioqK4uLgfHx9iYmLc3NwNDQ1ERE" +
                    "SWlpaBgYEPDw+5ubkrKyu+vr52dna0tLShoaEICAgqKirZ2dnr6+vU1NQcHBzR0dGkpKRlZWVHR0dFRU" +
                    "UuLi4ODg5SUlKoqKgyMjIRERFeXl6dnZ3DOIqjAAAAAXRSTlMAQObYZgAAAlpJREFUeNqF1elfEkEYB/" +
                    "BBczZUxgw6BCwqSQ1mVhLcxCArsCCL8CDKxDCPwCIMi4rQ7rL7sPOvbWYXZHfZpd+r/bBfltnneWYAQJ" +
                    "Gf4V+/IU15889foB/PFpQlH1zVZj8sUBVk1GBdW1AjLRNqdxBBzXCqh/ZCvaCk3H2D+kHfa+4LbBTH16" +
                    "r7bGsIIZqvwA5oy+snSysqOb/54yd3TjdrVg4GRViGk4TniU4w/oCgg7kmCAdzpQLv08x768g7DsIShZ" +
                    "sQ+iNL+WisnhJ+PFNcZLCfQgeFmH9dNL0J8UTpYuG37W4ySqG5DWzQ3vl9Pux++my9gIn8cc8zL17S7z" +
                    "IIX4ESFCGlT7rLU3FSpSQ+k40m2JUI18Uu+6VbwoOi6aEgUoIfpYoL0qpF+Bjc24Y0iQmLscAqtXY/v5" +
                    "KofChCBFJymBtbvpu3RsiqMzk3y8uhWQ5JYGk5LdzKmDzZldt3egxYAW/U1pj22NP0Z73zNxcwwQbnIq" +
                    "5BCKarkFybuT4kvQjPykRmU6P8NpwDkxWIQ1PTCUXB8ZXkVVYCETaDAQkS4eKlmKqDePhyvArpJrMxSP" +
                    "D5vkhdq4XoBW+lM+MAnGaQP+M6Wz86JBQeC4i9PkeHYpjBEddJrSEjgeApBlEnG8jjcJBgL9GEZEggJz" +
                    "hpcMEx6HJj/QHnBzjkkTZND3Ie7dVNn4Xrr+zCw//ZrtyR6sZu5VADh+yyI8rRQB6SHz7dnK47oDzOrH" +
                    "rrtANV9u7TYvu7NM7czt1mFbPs0Tns202ypaKOXQ3+FwxNzTtaaOV2GlvblHf+AYs3zFP1X7jmAAAAAE" +
                    "lFTkSuQmCC\",\r\n                \"logoAlt\": \"Email us\",\r\n                \"accountUr" +
                    "l\": \"");
            
            #line 119 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(other.EmailUsLink));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"shareUrl\": \"");
            
            #line 120 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(other.EmailUsLink));
            
            #line default
            #line hidden
            this.Write("\"\r\n            },\r\n");
            
            #line 122 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

            }
        }

        if (socialMedia != null)
        {
            var socialMediaState = socialMedia.WithState();

            foreach (var entry in socialMediaState)
            {

            
            #line default
            #line hidden
            this.Write("            {\r\n                \"visitTitle\": \"");
            
            #line 134 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.VisitCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"visitText\": \"");
            
            #line 135 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.VisitCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"shareTitle\": \"");
            
            #line 136 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.ShareCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"shareText\": \"");
            
            #line 137 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.ShareCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"tinyLogo\": \"");
            
            #line 138 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.TinyLogo));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"smallLogo\": \"");
            
            #line 139 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.SmallLogo));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"largeLogo\": \"");
            
            #line 140 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.LargeLogo));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"logoAlt\": \"");
            
            #line 141 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"accountUrl\": \"");
            
            #line 142 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.AccountUrl));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"shareUrl\": \"");
            
            #line 143 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.ShareUrl));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"enable\": \"");
            
            #line 144 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entry.Enable.ToString().LowerCase()));
            
            #line default
            #line hidden
            this.Write("\"\r\n            }");
            
            #line 145 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(socialMediaState.IsLast ? string.Empty : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 146 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

            }                                             
        }


            
            #line default
            #line hidden
            this.Write("        ],\r\n        \"appStoreLinks\":\r\n        [\r\n");
            
            #line 153 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

        if (appStores != null)
        {
            var appStoresState = appStores.WithState();

            foreach (var appStore in appStoresState)
            {

            
            #line default
            #line hidden
            this.Write("            {\r\n                \"name\": \"");
            
            #line 162 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"text\": \"");
            
            #line 163 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.CallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"title\": \"");
            
            #line 164 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.CallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"tinyLogo\": \"");
            
            #line 165 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.TinyLogo));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"smallLogo\": \"");
            
            #line 166 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.SmallLogo));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"largeLogo\": \"");
            
            #line 167 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.LargeLogo));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"logoAlt\": \"");
            
            #line 168 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"accountUrl\": \"");
            
            #line 169 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.AccountUrl));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"device\": \"");
            
            #line 170 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.DeviceRatingsOs));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"allowRating\": \"");
            
            #line 171 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStore.AllowRating.ToString().LowerCase()));
            
            #line default
            #line hidden
            this.Write("\"\r\n            }");
            
            #line 172 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(appStoresState.IsLast ? string.Empty : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 173 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

            }                                             
        }

            
            #line default
            #line hidden
            this.Write("        ],\r\n        \"tellOthers\":\r\n        [\r\n");
            
            #line 179 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

        if (other != null)
        {
            if (other.TellOthers != null)
            {
                var linkProperties = this.MarketingObjectProperties.GetLinkProperties("TellOthers", other.TellOthers.Url);

            
            #line default
            #line hidden
            this.Write("            {\r\n                \"visitTitle\": \"");
            
            #line 187 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"visitText\": \"");
            
            #line 188 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"smallLogo\": \"data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAA" +
                    "CAAAAAgCAMAAABEpIrGAAAALHRFWHRDcmVhdGlvbiBUaW1lAFNhdCAyMCBNYXIgMjAyMSAxMzoyODo0M" +
                    "CAtMDYwMO6DlpoAAAAHdElNRQflAxUTLRCJx6pOAAAACXBIWXMAAAsSAAALEgHS3X78AAAABGdBTUEAA" +
                    "LGPC/xhBQAAAv1QTFRFAP8AycnJAA4eAEeOAESIAEiQPz8/ICAgAB49AEiPAEOICQsMABAiAFKkAFGiA" +
                    "E6cAE+gABUrQkJC2dnZxMTEAChQABYt3t7eCQgJ+vr6AEeRAEyZREREACVMBgUF8vLyv7+/OTk5AAAAA" +
                    "gICFBAQBQYHAAkW0NDQwMDADxAQATFiBE+ZBgYG7e3tmZmZAQUNASNUASxpIRsb9sfH47i4LSUljIyMz" +
                    "c3NKSkpUVFRlpaWBA4XBVShBAYI5eXl1dXVBgkNAS9wAjmIAjBy7cDAh21tYmJiYSYkNBQTVFRUCBclb" +
                    "m5uABk8Ixwc9MbGjXJyLS0t6F1Y5lxXXV1dBVGcAAIGNTU1ASliATaBATiG+crKc11dZ2dnpaWlKxEQ7" +
                    "2BaRxwadi8s3llUCAUEBUmMARtBS0tMMTExAitnAS5uGhUVvZqal3t7DgsLqKioFRUVHgwLHx8fkJCQA" +
                    "xAcAjV/AAQKmqCoASJSAAYQAA0aABElcHBwrq6u3d3dAS1aAUCQABxFd3d3ARxDADt1AESHDQ4QAAgSA" +
                    "EuVoKCgABw4ABs2AAoYJiYnADVqACRJDQ0NgoKCADZtAj2NAShau7u7ATN6ABEptbW1HBwcADhvACNHA" +
                    "BY1BQQGACBNADJkACFC9vb2eXl5ABMuTzo64KSkxZCQLSEhAA0hTU1NhoaGFyErERERiWVl7a2t9rW1+" +
                    "La28rKyVT4+lJ6oHhgY2Z+f56qqhmNjxcfJMigo+MnJnoGBdFVVJRwcEQ4OCQcHQC8vWUFBxMrQFhIS6" +
                    "b299sjIe2NjKiIir46O8PT3IiQmBAQE8sTEzqenWUhI6+vr/v7+yKKiUkJCTT4+1KysnJycY1BQwp2d3" +
                    "LKyzKamWVlZDQsLQjAwfmZmNCoqEhUapYaGbVhYZ1NTPzQ0FhAQampqaExMbE9PQDQ0HiIqhpe5X2qDd" +
                    "4akfIysnHJyMyUlNjY2Sjw8fGVlERMYdIOhRU5gLiUlYm6IYW2GmHt7fn5+dl9fcVxcmn19OC4uvb29R" +
                    "N0UsQAAAAF0Uk5TAEDm2GYAAAL9SURBVHjaY2CAAeFDx47/+uWvoijPgBUI57v6nT4TFXX4rOICbPI/f" +
                    "+38ve/YjfuHVP4Y//3HwKBUWFiIJF37XufDx0+fv3y99e37rR++tzyVzkucP4+k5snTZ8eev3j5SkXi9" +
                    "RuJiypv3ymd1zwPAjAVZstu33G5e4/7/oPW1oc7Hx14POF8IUSBHESB5BXFq1F+165HRd24EbXT96bSe" +
                    "T2rW+fP5+fnFcEsYTQ6HQX0wq6dUVGXV0sq5p8/L6xUOOH8eSW4OxVdd0ZdULl4Osr40kKgH8AWKJ0vw" +
                    "hkOhcrnzp0Xt1JC8iooJP1cYCF54mShsnLhKWQFDBa79+zdt/9ADJhz8NBhlyNRR1eiKFi6YcvW9dsgC" +
                    "rbvcAG6d9cEuKykudXqNWvXrd+wMb2jFsjfJLcZCFQgChZMX8jWr7+ooWLxkqXLljdVheavWLmqwdnZO" +
                    "bMNbNz0GTx9M2epTY0omZ07Z26Ek2Gp1rz5VRFOTpHlSnlA+SkOE/l4eXn71KZmdisWTptqWDqRl59Xw" +
                    "MnJKaJNURJoeU8vSJ6Pv0+/f0KtfbB+KVg97yQnp8nsdkADRLoh8nwtmhriQKDXxs8PUsDv5MQUC3KBV" +
                    "SdYnpe3q1ocDBTrwDr4+MQCJEEKGpvqZZv5+XhbWtUhCvLa2oEKBPidSjvAfvQ0cCqvqOQRq6oWN6+pt" +
                    "c8TFg+rA1lR32ABNoAhPSMyIjMrOyc3jzG/gK2wIEy8qBikoKS0DBKEYeERkc6+UX7RMbFx8QmJScnC9" +
                    "hIpQCtS06Bh7O3j5OTsC4xGN/sA98Agj2Bxe+UQXl6pUEaoAnsHRydnIxdjVzdxcwt3D09hcUY5oDe83" +
                    "ODRpKdvYGhkbGJqJg5UYSksLm5lzctrY2uHiGYFRSVlFVU1IaCcOhBraGrx8mrr6CIlBEYmKSlpfkEZY" +
                    "VAwiLDL8goIMMsh51BGHlBY8ouBzBBhFwWFO6uEJKoCoBivgKCQMFSel5+bAcUKZhZmVlZWFiY2dg5OM" +
                    "JsLrgAAdIsJbsoPeAIAAAAASUVORK5CYII=\",\r\n                \"logoAlt\": \"Tell others\"," +
                    "\r\n                \"accountUrl\": \"");
            
            #line 191 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(other.TellOthers.Url));
            
            #line default
            #line hidden
            this.Write("\"\r\n            }\r\n");
            
            #line 193 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("        ],\r\n        \"sidelLinks\":\r\n        [\r\n");
            
            #line 200 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

        if (otherLinks != null)
        {
            var otherLinksState = otherLinks.WithState();

            foreach (var link in otherLinksState)
            {
                var linkProperties = this.MarketingObjectProperties.GetLinkProperties("Other", link);

            
            #line default
            #line hidden
            this.Write("            {\r\n                \"title\": \"");
            
            #line 210 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"text\": \"");
            
            #line 211 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(linkProperties.LinkCallToAction));
            
            #line default
            #line hidden
            this.Write("\",\r\n                \"url\": \"");
            
            #line 212 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(link));
            
            #line default
            #line hidden
            this.Write("\"\r\n            }");
            
            #line 213 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(otherLinksState.IsLast ? string.Empty : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 214 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("        ]\r\n");
            
            #line 219 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("        \"mainPageLinks\":\r\n        [\r\n\r\n        ],\r\n        \"socialLinks\":\r\n      " +
                    "  [\r\n        ],\r\n        \"sidelLinks\":\r\n        [\r\n        ]\r\n");
            
            #line 234 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("      }\r\n    }\r\n  ],\r\n  \"license\":\r\n  [\r\n    {\r\n      \"page\":\r\n      {\r\n        \"" +
                    "pageTitle\": \"Licensing information for the ");
            
            #line 245 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"metaDescription\": \"\",\r\n        \"metaKeywords\": \"\"\r\n      },\r\n      \"" +
                    "details\":\r\n      {\r\n        \"content\": \"");
            
            #line 251 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.GetHtmlContent("EndUserLicense")));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"licenseUrl\": \"");
            
            #line 252 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.EndUserLicenseUrl.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"licenseUrlTitle\": \"This is the EULA (end user license agreement) for" +
                    " using of ");
            
            #line 253 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"questionsEmailAddress\": \"");
            
            #line 254 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.EndUserLicenseEmailAddress.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"questionsEmailAddressTitle\": \"You can submit email questions regardi" +
                    "ng the usage of ");
            
            #line 255 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write(" by clicking this link\",\r\n        \"questionsMailingAddress\": \"");
            
            #line 256 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.EndUserLicenseMailingAddress.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\"\r\n      }\r\n    }\r\n  ],\r\n  \"support\":\r\n  [\r\n    {\r\n      \"page\":\r\n      {\r\n      " +
                    "  \"pageTitle\": \"Support information for the ");
            
            #line 265 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"metaDescription\": \"\",\r\n        \"metaKeywords\": \"\"\r\n      },\r\n      \"" +
                    "details\":\r\n      {\r\n        \"content\": \"");
            
            #line 271 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.GetHtmlContent("SupportDetails")));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"supportUrl\": \"");
            
            #line 272 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.SupportUrl.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"supportUrlTitle\": \"This is the link for support details for usage of" +
                    " ");
            
            #line 273 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"supportEmailAddress\": \"");
            
            #line 274 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.SupportEmailAddress.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write("\",\r\n        \"supportEmailAddressTitle\": \"You can submit email questions to retrie" +
                    "ve support for the ");
            
            #line 275 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ResourceData.AppName.NullToEmpty()));
            
            #line default
            #line hidden
            this.Write(" by clicking this link\"\r\n      }\r\n    }\r\n  ],\r\n  \"pages\":\r\n  [\r\n  ]\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Client\Theme\DataJsonTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::AbstraX.IResourceData _ResourceDataField;

/// <summary>
/// Access the ResourceData parameter of the template.
/// </summary>
private global::AbstraX.IResourceData ResourceData
{
    get
    {
        return this._ResourceDataField;
    }
}

private global::AbstraX.ObjectProperties.MarketingObjectProperties _MarketingObjectPropertiesField;

/// <summary>
/// Access the MarketingObjectProperties parameter of the template.
/// </summary>
private global::AbstraX.ObjectProperties.MarketingObjectProperties MarketingObjectProperties
{
    get
    {
        return this._MarketingObjectPropertiesField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool ResourceDataValueAcquired = false;
if (this.Session.ContainsKey("ResourceData"))
{
    this._ResourceDataField = ((global::AbstraX.IResourceData)(this.Session["ResourceData"]));
    ResourceDataValueAcquired = true;
}
if ((ResourceDataValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ResourceData");
    if ((data != null))
    {
        this._ResourceDataField = ((global::AbstraX.IResourceData)(data));
    }
}
bool MarketingObjectPropertiesValueAcquired = false;
if (this.Session.ContainsKey("MarketingObjectProperties"))
{
    this._MarketingObjectPropertiesField = ((global::AbstraX.ObjectProperties.MarketingObjectProperties)(this.Session["MarketingObjectProperties"]));
    MarketingObjectPropertiesValueAcquired = true;
}
if ((MarketingObjectPropertiesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("MarketingObjectProperties");
    if ((data != null))
    {
        this._MarketingObjectPropertiesField = ((global::AbstraX.ObjectProperties.MarketingObjectProperties)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
