taskkill /f /im ApplicationGenerator.exe
taskkill /f /im NetCoreReflectionShim.Service.exe
taskkill /f /im HydraCrashAnalyzer.exe
taskkill /f /im HydraCrashAnalyzer.Core.exe
taskkill /f /im HydraDesktop.exe
taskkill /f /im MSIExec.exe
taskkill /f /im MSBuild.exe
taskkill /f /im Node.exe
taskkill /f /im TGitCache.exe
