// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AbstraX.Generators.Client.EntityProvider
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using AbstraX.Generators;
    using AbstraX.Angular;
    using AbstraX.DataAnnotations;
    using AbstraX;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EntityProviderClassTemplate : AbstraX.Generators.Base.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 24 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
 
    var providerName = this.ProviderName.ToCamelCase();
    var className = this.ProviderName + "Provider";
    var provider = new EntityProvider(className);
    var modelVariable = this.EntityName.ToCamelCase();
    var modelVariablePlural = this.EntityName.Pluralize();
    var lambdaParameter = modelVariable.Left(1);

    this.Providers.Add(provider);

    foreach (var import in this.Imports)
    {
        this.WriteLine(import.DeclarationCode);
    }

            
            #line default
            #line hidden
            this.Write(@"import 'rxjs/add/operator/toPromise';
import { Injectable, Injector, ComponentFactoryResolver, Type } from '@angular/core';
import { Api } from './api/api';
import { AccessTokenInfo } from '../models/accesstokeninfo.model';
import { ViewController, Nav } from 'ionic-angular';
import { App } from 'ionic-angular/components/app/app';
import { NavControllerBase } from 'ionic-angular/navigation/nav-controller-base';

@Injectable()
export class ");
            
            #line 48 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" {\r\n  ");
            
            #line 49 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 49 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 50 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

    if (this.IsIdentityEntity)
    {

            
            #line default
            #line hidden
            this.Write("  clientId: string = \"");
            
            #line 54 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClientId));
            
            #line default
            #line hidden
            this.Write("\";\r\n  clientSecret: string = \"");
            
            #line 55 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClientSecret));
            
            #line default
            #line hidden
            this.Write("\";\r\n  public accessTokenInfo: AccessTokenInfo;\r\n  private navController : NavCont" +
                    "rollerBase;\r\n  private roles : List<string>;\r\n\r\n  constructor(public api: Api, p" +
                    "rivate app: App, private componentFactoryResolver: ComponentFactoryResolver, pri" +
                    "vate injector: Injector)\r\n  {\r\n  }\r\n\r\n  login(accountInfo: { userName: string, p" +
                    "assword: string }) {\r\n    let authorizationBasic = btoa(this.clientId + \':\' + th" +
                    "is.clientSecret);\r\n    let seq = this.api.authenticate(\'oauth/token\', accountInf" +
                    "o, authorizationBasic).share();\r\n\r\n    seq.subscribe((res: any) => {\r\n      if (" +
                    "res.access_token !== undefined || res.error !== undefined) {\r\n\r\n        this.log" +
                    "gedIn(res);\r\n      } else {\r\n      }\r\n    }, err => {\r\n      console.error(\'ERRO" +
                    "R\', err);\r\n    });\r\n\r\n    return seq;\r\n  }\r\n\r\n  register(accountInfo: any) {\r\n  " +
                    "  let seq = this.api.post(\'register\', accountInfo).share();\r\n\r\n    seq.subscribe" +
                    "((res: any) => {\r\n\r\n      if (res.status == \'success\') {\r\n        this.loggedIn(" +
                    "res);\r\n      }\r\n    }, err => {\r\n      console.error(\'ERROR\', err);\r\n    });\r\n\r\n" +
                    "    return seq;\r\n  }\r\n\r\n  logout() {\r\n    this.accessTokenInfo = null;\r\n    this" +
                    ".api.accessToken = null;\r\n  }\r\n\r\n  loggedIn(resp) {\r\n    let rolesString : strin" +
                    "g = resp.roles;\r\n\r\n    this.accessTokenInfo = new AccessTokenInfo(resp);\r\n    th" +
                    "is.api.accessToken = this.accessTokenInfo.accessToken;\r\n    this.roles = new Lis" +
                    "t<string>(rolesString.split(\",\"));\r\n  }\r\n\r\n  canView(enteringView: ViewControlle" +
                    "r, leavingView: ViewController, ti: any) : Promise<boolean> {\r\n\r\n    if (enterin" +
                    "gView) {\r\n      try {\r\n        let name = enteringView.name;\r\n        let getCom" +
                    "ponentByName : (name: string) => any = window[\"_getComponentByName\"]\r\n\r\n        " +
                    "return getComponentByName(name).then(c =>\r\n        {\r\n          if (c[\"Authorize" +
                    "dFor\"]) {\r\n\r\n            let authorizedFor = new List<string>(c[\"AuthorizedFor\"]" +
                    ");\r\n            let rootNav = <Nav> this.app.getRootNav();\r\n\r\n            if (c." +
                    "name == rootNav.root && !this.accessTokenInfo) {\r\n              rootNav.push(\"Lo" +
                    "ginPage\");\r\n              return Promise.resolve(false);\r\n            }\r\n\r\n     " +
                    "       if (authorizedFor.any(a => this.roles.any(r => r == a))) {\r\n             " +
                    " return Promise.resolve(true);\r\n            }\r\n            else {\r\n             " +
                    " throw `User not authorized for ${ name }`;\r\n            }\r\n          }\r\n       " +
                    " })\r\n      }\r\n      catch (e) {\r\n        console.error(e);\r\n      }\r\n    }\r\n\r\n  " +
                    "  return Promise.resolve(true);\r\n  }\r\n");
            
            #line 144 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("\r\n  constructor(public api: Api)\r\n  {\r\n  }\r\n");
            
            #line 153 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

    }

    if (this.CustomQueries != null)
    {
        foreach (var query in this.CustomQueries)
        {
            var queryModelVariable = query.QueryEntityName;
            var queryLambdaParameter = modelVariable.Left(1);

            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 164 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.ClientProviderMethodName));
            
            #line default
            #line hidden
            this.Write("() {\r\n    let observable = this.api.get<");
            
            #line 165 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.ClientProviderApiMethodReturnType));
            
            #line default
            #line hidden
            this.Write(">(\'");
            
            #line 165 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.ClientProviderMethodName));
            
            #line default
            #line hidden
            this.Write("\');\r\n\r\n");
            
            #line 167 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

            if (query.ReturnsSet)
            {

            
            #line default
            #line hidden
            this.Write("    \r\n    return observable.map(");
            
            #line 171 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryLambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 171 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryLambdaParameter));
            
            #line default
            #line hidden
            this.Write(".map(");
            
            #line 171 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryLambdaParameter));
            
            #line default
            #line hidden
            this.Write("2 => new ");
            
            #line 171 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.QueryEntityName));
            
            #line default
            #line hidden
            this.Write("(<any>");
            
            #line 171 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryLambdaParameter));
            
            #line default
            #line hidden
            this.Write("2)));\r\n");
            
            #line 172 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("    return observable.map(");
            
            #line 177 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryLambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => new ");
            
            #line 177 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(query.QueryEntityName));
            
            #line default
            #line hidden
            this.Write("(<any>");
            
            #line 177 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryLambdaParameter));
            
            #line default
            #line hidden
            this.Write("));  \r\n  }\r\n");
            
            #line 179 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

            }
        }
    }

    foreach (var relatedEntity in this.RelatedEntities)
    {
        var property = relatedEntity.Name;
        var propertyVariable = relatedEntity.Name.ToCamelCase();

        if (relatedEntity.IsEntitySet)
        {

            
            #line default
            #line hidden
            this.Write("\r\n  get");
            
            #line 193 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property));
            
            #line default
            #line hidden
            this.Write("() {\r\n    let observable = this.api.get<");
            
            #line 194 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("[]>(\'");
            
            #line 194 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyVariable));
            
            #line default
            #line hidden
            this.Write("\');\r\n\r\n    return observable.map(");
            
            #line 196 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 196 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".map(");
            
            #line 196 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write("2 => new ");
            
            #line 196 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(<any>");
            
            #line 196 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write("2)));\r\n  }\r\n\r\n");
            
            #line 199 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

        }
        else
        {
            var parentRefName = relatedEntity.EntityParentRef.Name;
            var parentRefVariableName = parentRefName.ToCamelCase();
            var propertyRefVariableName = relatedEntity.ThisPropertyRef.Name.ToCamelCase();
            var scriptType = relatedEntity.ThisPropertyRefScriptType;
            var shortType = relatedEntity.ThisPropertyRefShortType;
            var containerSetName = relatedEntity.ContainerSet.Name;

            
            #line default
            #line hidden
            this.Write("  get");
            
            #line 210 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property));
            
            #line default
            #line hidden
            this.Write("For");
            
            #line 210 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentRefName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 210 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyRefVariableName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 210 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(scriptType));
            
            #line default
            #line hidden
            this.Write(") {\r\n    let observable = this.api.get<");
            
            #line 211 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("[]>(`");
            
            #line 211 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("{0}/${{{1}}}/{2}", containerSetName.ToCamelCase(), propertyRefVariableName, propertyVariable)));
            
            #line default
            #line hidden
            this.Write("`);\r\n\r\n    return observable.map(");
            
            #line 213 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 213 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(".map(");
            
            #line 213 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write("2 => new ");
            
            #line 213 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(<any>");
            
            #line 213 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write("2)));\r\n  }\r\n\r\n");
            
            #line 216 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("  get");
            
            #line 220 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(id: string){\r\n    let observable = this.api.get<");
            
            #line 221 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(">(`");
            
            #line 221 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/${id}`);\r\n\r\n    return observable.map(");
            
            #line 223 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write(" => new ");
            
            #line 223 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(<any>");
            
            #line 223 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lambdaParameter));
            
            #line default
            #line hidden
            this.Write("));\r\n  }\r\n\r\n  create");
            
            #line 226 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 226 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 226 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("){\r\n    let observable = this.api.post(\'");
            
            #line 227 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("\', ");
            
            #line 227 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n    return observable;\r\n  }\r\n\r\n  update");
            
            #line 232 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 232 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 232 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(") {\r\n    let observable = this.api.put(\'");
            
            #line 233 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("\', ");
            
            #line 233 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n    return observable;\r\n  }\r\n\r\n  delete");
            
            #line 238 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(id: string): any {\r\n    let observable = this.api.delete(\'");
            
            #line 239 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("?id=\' + id);\r\n\r\n    return observable;\r\n  }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Client\EntityProvider\EntityProviderClassTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration> _ImportsField;

/// <summary>
/// Access the Imports parameter of the template.
/// </summary>
private global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration> Imports
{
    get
    {
        return this._ImportsField;
    }
}

private global::System.Collections.Generic.List<ESModule> _ExportsField;

/// <summary>
/// Access the Exports parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<ESModule> Exports
{
    get
    {
        return this._ExportsField;
    }
}

private global::System.Collections.Generic.List<IDeclarable> _DeclarationsField;

/// <summary>
/// Access the Declarations parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<IDeclarable> Declarations
{
    get
    {
        return this._DeclarationsField;
    }
}

private global::System.Collections.Generic.List<Provider> _ProvidersField;

/// <summary>
/// Access the Providers parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<Provider> Providers
{
    get
    {
        return this._ProvidersField;
    }
}

private global::System.Collections.Generic.List<RelatedEntity> _RelatedEntitiesField;

/// <summary>
/// Access the RelatedEntities parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<RelatedEntity> RelatedEntities
{
    get
    {
        return this._RelatedEntitiesField;
    }
}

private global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo> _CustomQueriesField;

/// <summary>
/// Access the CustomQueries parameter of the template.
/// </summary>
private global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo> CustomQueries
{
    get
    {
        return this._CustomQueriesField;
    }
}

private string _ProviderNameField;

/// <summary>
/// Access the ProviderName parameter of the template.
/// </summary>
private string ProviderName
{
    get
    {
        return this._ProviderNameField;
    }
}

private string _EntityNameField;

/// <summary>
/// Access the EntityName parameter of the template.
/// </summary>
private string EntityName
{
    get
    {
        return this._EntityNameField;
    }
}

private bool _IsIdentityEntityField;

/// <summary>
/// Access the IsIdentityEntity parameter of the template.
/// </summary>
private bool IsIdentityEntity
{
    get
    {
        return this._IsIdentityEntityField;
    }
}

private string _ClientIdField;

/// <summary>
/// Access the ClientId parameter of the template.
/// </summary>
private string ClientId
{
    get
    {
        return this._ClientIdField;
    }
}

private string _ClientSecretField;

/// <summary>
/// Access the ClientSecret parameter of the template.
/// </summary>
private string ClientSecret
{
    get
    {
        return this._ClientSecretField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool ImportsValueAcquired = false;
if (this.Session.ContainsKey("Imports"))
{
    this._ImportsField = ((global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration>)(this.Session["Imports"]));
    ImportsValueAcquired = true;
}
if ((ImportsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Imports");
    if ((data != null))
    {
        this._ImportsField = ((global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration>)(data));
    }
}
bool ExportsValueAcquired = false;
if (this.Session.ContainsKey("Exports"))
{
    this._ExportsField = ((global::System.Collections.Generic.List<ESModule>)(this.Session["Exports"]));
    ExportsValueAcquired = true;
}
if ((ExportsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Exports");
    if ((data != null))
    {
        this._ExportsField = ((global::System.Collections.Generic.List<ESModule>)(data));
    }
}
bool DeclarationsValueAcquired = false;
if (this.Session.ContainsKey("Declarations"))
{
    this._DeclarationsField = ((global::System.Collections.Generic.List<IDeclarable>)(this.Session["Declarations"]));
    DeclarationsValueAcquired = true;
}
if ((DeclarationsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Declarations");
    if ((data != null))
    {
        this._DeclarationsField = ((global::System.Collections.Generic.List<IDeclarable>)(data));
    }
}
bool ProvidersValueAcquired = false;
if (this.Session.ContainsKey("Providers"))
{
    this._ProvidersField = ((global::System.Collections.Generic.List<Provider>)(this.Session["Providers"]));
    ProvidersValueAcquired = true;
}
if ((ProvidersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Providers");
    if ((data != null))
    {
        this._ProvidersField = ((global::System.Collections.Generic.List<Provider>)(data));
    }
}
bool RelatedEntitiesValueAcquired = false;
if (this.Session.ContainsKey("RelatedEntities"))
{
    this._RelatedEntitiesField = ((global::System.Collections.Generic.List<RelatedEntity>)(this.Session["RelatedEntities"]));
    RelatedEntitiesValueAcquired = true;
}
if ((RelatedEntitiesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RelatedEntities");
    if ((data != null))
    {
        this._RelatedEntitiesField = ((global::System.Collections.Generic.List<RelatedEntity>)(data));
    }
}
bool CustomQueriesValueAcquired = false;
if (this.Session.ContainsKey("CustomQueries"))
{
    this._CustomQueriesField = ((global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo>)(this.Session["CustomQueries"]));
    CustomQueriesValueAcquired = true;
}
if ((CustomQueriesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("CustomQueries");
    if ((data != null))
    {
        this._CustomQueriesField = ((global::System.Collections.Generic.IEnumerable<AbstraX.QueryInfo>)(data));
    }
}
bool ProviderNameValueAcquired = false;
if (this.Session.ContainsKey("ProviderName"))
{
    this._ProviderNameField = ((string)(this.Session["ProviderName"]));
    ProviderNameValueAcquired = true;
}
if ((ProviderNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ProviderName");
    if ((data != null))
    {
        this._ProviderNameField = ((string)(data));
    }
}
bool EntityNameValueAcquired = false;
if (this.Session.ContainsKey("EntityName"))
{
    this._EntityNameField = ((string)(this.Session["EntityName"]));
    EntityNameValueAcquired = true;
}
if ((EntityNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityName");
    if ((data != null))
    {
        this._EntityNameField = ((string)(data));
    }
}
bool IsIdentityEntityValueAcquired = false;
if (this.Session.ContainsKey("IsIdentityEntity"))
{
    this._IsIdentityEntityField = ((bool)(this.Session["IsIdentityEntity"]));
    IsIdentityEntityValueAcquired = true;
}
if ((IsIdentityEntityValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("IsIdentityEntity");
    if ((data != null))
    {
        this._IsIdentityEntityField = ((bool)(data));
    }
}
bool ClientIdValueAcquired = false;
if (this.Session.ContainsKey("ClientId"))
{
    this._ClientIdField = ((string)(this.Session["ClientId"]));
    ClientIdValueAcquired = true;
}
if ((ClientIdValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ClientId");
    if ((data != null))
    {
        this._ClientIdField = ((string)(data));
    }
}
bool ClientSecretValueAcquired = false;
if (this.Session.ContainsKey("ClientSecret"))
{
    this._ClientSecretField = ((string)(this.Session["ClientSecret"]));
    ClientSecretValueAcquired = true;
}
if ((ClientSecretValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ClientSecret");
    if ((data != null))
    {
        this._ClientSecretField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
