// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AbstraX.Generators.Pages.TabPage
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using AbstraX.Generators;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TabPageTemplate : AbstraX.Generators.Base.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<ion-tabs>\r\n  <ion-tab-bar slot=\"bottom\">\r\n");
            
            #line 14 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"
 
    foreach (var tab in this.Tabs) 
    {

            
            #line default
            #line hidden
            this.Write("      <ion-tab [root]=\"");
            
            #line 18 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tab.Root.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Root\" [tabTitle]=\"");
            
            #line 18 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tab.Title.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Title\" ");
            
            #line 18 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"
 if (tab.Icon != null)
        {
 
            
            #line default
            #line hidden
            this.Write(" tabIcon=\"");
            
            #line 20 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tab.Icon));
            
            #line default
            #line hidden
            this.Write("\"></ion-tab>\r\n");
            
            #line 21 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"

        }
        else
        {
 
            
            #line default
            #line hidden
            this.Write("></ion-tab>");
            
            #line 25 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"

         }
    }

            
            #line default
            #line hidden
            this.Write("  </ion-tab-bar>\r\n</ion-tabs>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\CloudIDEaaS\root\ApplicationGenerator.IonicAngular\Generators\Pages\TabPage\TabPageTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::System.Collections.Generic.List<Tab> _TabsField;

/// <summary>
/// Access the Tabs parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<Tab> Tabs
{
    get
    {
        return this._TabsField;
    }
}

private string _PageNameField;

/// <summary>
/// Access the PageName parameter of the template.
/// </summary>
private string PageName
{
    get
    {
        return this._PageNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool TabsValueAcquired = false;
if (this.Session.ContainsKey("Tabs"))
{
    this._TabsField = ((global::System.Collections.Generic.List<Tab>)(this.Session["Tabs"]));
    TabsValueAcquired = true;
}
if ((TabsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Tabs");
    if ((data != null))
    {
        this._TabsField = ((global::System.Collections.Generic.List<Tab>)(data));
    }
}
bool PageNameValueAcquired = false;
if (this.Session.ContainsKey("PageName"))
{
    this._PageNameField = ((string)(this.Session["PageName"]));
    PageNameValueAcquired = true;
}
if ((PageNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("PageName");
    if ((data != null))
    {
        this._PageNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
