// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AbstraX.Generators.Pages.EditPopupPage
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using AbstraX;
    using AbstraX.Generators;
    using AbstraX.Angular;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EditPopupClassTemplate : AbstraX.Generators.Base.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 19 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
 
    var pageName = this.PageName.ToCamelCase();
    var className = "Edit" + this.PageName + "Page";
    var component = new Page(className);
    var modelVariable = this.EntityName.ToCamelCase();
    var builder = new StringBuilder();

    this.Declarations.Add(component);
    this.Exports.Add(component);

    foreach (var import in this.Imports)
    {
        this.WriteLine(import.DeclarationCode);
    }

            
            #line default
            #line hidden
            this.Write("\r\n@IonicPage()\r\n");
            
            #line 36 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
 if (this.Authorize.Length > 0)
   {

            
            #line default
            #line hidden
            this.Write("@Authorize(\"");
            
            #line 39 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Authorize));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 40 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
 
   }

            
            #line default
            #line hidden
            this.Write("@Component({\r\n  selector: \'page-edit-");
            
            #line 44 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageName));
            
            #line default
            #line hidden
            this.Write("\',\r\n  templateUrl: \'edit-");
            
            #line 45 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pageName));
            
            #line default
            #line hidden
            this.Write(".html\'\r\n})\r\nexport class ");
            
            #line 47 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" extends UsablePopover {\r\n\r\n  userAction: string;\r\n  ");
            
            #line 50 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form: FormGroup;\r\n  masks: any;\r\n");
            
            #line 52 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    foreach (var formField in this.FormFields.GetKeyOrDisplayed())
    {

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 56 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MakeVariable(modelVariable, formField.Name)));
            
            #line default
            #line hidden
            this.Write(": string;\r\n");
            
            #line 57 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n  constructor(public navCtrl: NavController,\r\n    public navParams: NavParams,\r" +
                    "\n    public toastCtrl: ToastController,\r\n    public ");
            
            #line 64 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider: ");
            
            #line 64 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Provider,\r\n    public ");
            
            #line 65 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Validator: ");
            
            #line 65 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Validator,\r\n    public viewCtrl: ViewController,\r\n    public translateService: Tr" +
                    "anslateService) {\r\n\r\n      super();\r\n\r\n      this.masks = {\r\n");
            
            #line 72 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    foreach (var formField in this.FormFields.GetMasked())
    {
        var validationSet = formField.ValidationSet;
        var validationElement = validationSet.PreferredValidationElement;
        var validationMask = validationSet.PreferredValidationMask;

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 79 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(validationMask.Name));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 79 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(validationMask.MaskExpression));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 80 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("      };\r\n\r\n      this.");
            
            #line 85 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form = null;\r\n  }\r\n\r\n  ngOnInit() {\r\n\r\n    var ");
            
            #line 90 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(" = <");
            
            #line 90 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(">this.navParams.get(\"");
            
            #line 90 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("\");\r\n\r\n    if (");
            
            #line 92 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(" !== undefined) {\r\n");
            
            #line 93 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    foreach (var formField in this.FormFields.GetKeyOrDisplayed())
    {

            
            #line default
            #line hidden
            this.Write("        this.");
            
            #line 97 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MakeVariable(modelVariable, formField.Name)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 97 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 97 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MakeVariable(modelVariable, formField.Name)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 98 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n");
            
            #line 103 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    foreach (var formField in this.FormFields.GetDisplayed())
    {
        builder.AppendWithLeadingIfLength(", ", string.Format("this.{0}", this.MakeVariable(modelVariable, formField.Name)));
    }

            
            #line default
            #line hidden
            this.Write("\r\n    this.userAction = this.navParams.get(\"userAction\");\r\n    this.");
            
            #line 111 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form = this.");
            
            #line 111 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Validator.create");
            
            #line 111 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("Form(");
            
            #line 111 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(builder.ToString()));
            
            #line default
            #line hidden
            this.Write(");\r\n  }\r\n\r\n  ionViewDidLoad() {\r\n    super.ionViewDidLoad();\r\n  }\r\n\r\n  submit({ v" +
                    "alue, valid }: { value: any, valid: boolean }) {\r\n\r\n    let providerFunction: (");
            
            #line 120 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 120 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(") => Observable<ArrayBuffer>;\r\n\r\n    if (this.userAction == \"New ");
            
            #line 122 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\") {\r\n      providerFunction = this.");
            
            #line 123 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider.create");
            
            #line 123 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n    }\r\n    else if (this.userAction == \"Edit ");
            
            #line 125 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("\") {\r\n      providerFunction = this.");
            
            #line 126 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider.update");
            
            #line 126 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write(";\r\n    }\r\n    else {\r\n      throw \"Invalid user action\";\r\n    }\r\n\r\n    providerFu" +
                    "nction = providerFunction.bind(this.");
            
            #line 132 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Provider);\r\n\r\n    if (!this.");
            
            #line 134 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form.invalid) {\r\n\r\n      let observable = providerFunction(new ");
            
            #line 136 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EntityName));
            
            #line default
            #line hidden
            this.Write("(\r\n      {\r\n");
            
            #line 138 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

    foreach (var formField in this.FormFields.GetKeyOrDisplayed())
    {
        var parmName = formField.Name.ToCamelCase();
        var name = formField.Name;
        var mask = formField.ValidationSet.PreferredValidationMask;

        if (mask != null)
        {

            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 148 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parmName));
            
            #line default
            #line hidden
            this.Write(": this.");
            
            #line 148 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form.get(\"");
            
            #line 148 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MakeVariable(modelVariable, name)));
            
            #line default
            #line hidden
            this.Write("\").value.replace(");
            
            #line 148 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mask.UnmaskExpression));
            
            #line default
            #line hidden
            this.Write(", \"\"),\r\n");
            
            #line 149 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 154 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parmName));
            
            #line default
            #line hidden
            this.Write(": this.");
            
            #line 154 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelVariable));
            
            #line default
            #line hidden
            this.Write("Form.get(\"");
            
            #line 154 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MakeVariable(modelVariable, name)));
            
            #line default
            #line hidden
            this.Write("\").value,\r\n");
            
            #line 155 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write(@"      }));

      observable.subscribe((response) => {
        this.viewCtrl.dismiss();
      }, err => {
        let toast = this.toastCtrl.create({
          message: err.message,
          duration: 3000,
          position: ""top""
        });
        toast.present();
      });
    }
  }
}
");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\RazorViewsDesigner\ApplicationGenerator\Generators\Pages\EditPopupPage\EditPopupClassTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::System.Collections.Generic.List<FormField> _FormFieldsField;

/// <summary>
/// Access the FormFields parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<FormField> FormFields
{
    get
    {
        return this._FormFieldsField;
    }
}

private global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration> _ImportsField;

/// <summary>
/// Access the Imports parameter of the template.
/// </summary>
private global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration> Imports
{
    get
    {
        return this._ImportsField;
    }
}

private global::System.Collections.Generic.List<ESModule> _ExportsField;

/// <summary>
/// Access the Exports parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<ESModule> Exports
{
    get
    {
        return this._ExportsField;
    }
}

private global::System.Collections.Generic.List<IDeclarable> _DeclarationsField;

/// <summary>
/// Access the Declarations parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<IDeclarable> Declarations
{
    get
    {
        return this._DeclarationsField;
    }
}

private string _PageNameField;

/// <summary>
/// Access the PageName parameter of the template.
/// </summary>
private string PageName
{
    get
    {
        return this._PageNameField;
    }
}

private string _AuthorizeField;

/// <summary>
/// Access the Authorize parameter of the template.
/// </summary>
private string Authorize
{
    get
    {
        return this._AuthorizeField;
    }
}

private string _EntityNameField;

/// <summary>
/// Access the EntityName parameter of the template.
/// </summary>
private string EntityName
{
    get
    {
        return this._EntityNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool FormFieldsValueAcquired = false;
if (this.Session.ContainsKey("FormFields"))
{
    this._FormFieldsField = ((global::System.Collections.Generic.List<FormField>)(this.Session["FormFields"]));
    FormFieldsValueAcquired = true;
}
if ((FormFieldsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FormFields");
    if ((data != null))
    {
        this._FormFieldsField = ((global::System.Collections.Generic.List<FormField>)(data));
    }
}
bool ImportsValueAcquired = false;
if (this.Session.ContainsKey("Imports"))
{
    this._ImportsField = ((global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration>)(this.Session["Imports"]));
    ImportsValueAcquired = true;
}
if ((ImportsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Imports");
    if ((data != null))
    {
        this._ImportsField = ((global::System.Collections.Generic.IEnumerable<ModuleImportDeclaration>)(data));
    }
}
bool ExportsValueAcquired = false;
if (this.Session.ContainsKey("Exports"))
{
    this._ExportsField = ((global::System.Collections.Generic.List<ESModule>)(this.Session["Exports"]));
    ExportsValueAcquired = true;
}
if ((ExportsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Exports");
    if ((data != null))
    {
        this._ExportsField = ((global::System.Collections.Generic.List<ESModule>)(data));
    }
}
bool DeclarationsValueAcquired = false;
if (this.Session.ContainsKey("Declarations"))
{
    this._DeclarationsField = ((global::System.Collections.Generic.List<IDeclarable>)(this.Session["Declarations"]));
    DeclarationsValueAcquired = true;
}
if ((DeclarationsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Declarations");
    if ((data != null))
    {
        this._DeclarationsField = ((global::System.Collections.Generic.List<IDeclarable>)(data));
    }
}
bool PageNameValueAcquired = false;
if (this.Session.ContainsKey("PageName"))
{
    this._PageNameField = ((string)(this.Session["PageName"]));
    PageNameValueAcquired = true;
}
if ((PageNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("PageName");
    if ((data != null))
    {
        this._PageNameField = ((string)(data));
    }
}
bool AuthorizeValueAcquired = false;
if (this.Session.ContainsKey("Authorize"))
{
    this._AuthorizeField = ((string)(this.Session["Authorize"]));
    AuthorizeValueAcquired = true;
}
if ((AuthorizeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Authorize");
    if ((data != null))
    {
        this._AuthorizeField = ((string)(data));
    }
}
bool EntityNameValueAcquired = false;
if (this.Session.ContainsKey("EntityName"))
{
    this._EntityNameField = ((string)(this.Session["EntityName"]));
    EntityNameValueAcquired = true;
}
if ((EntityNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityName");
    if ((data != null))
    {
        this._EntityNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
