# Default values for hydradevops-info.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: hydradevops-services
replicaCount: 1
image:
  repository: invalid
  tag: invalid
  pullPolicy: Always
imagePullSecrets: 
- name: container-registry-secret
service:
  port: 80

probes:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - www.cloudideaas.com
  paths:
    - /cloudideaas/hydradevops/services
    - /cloudideaas/hydradevops/services*
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
secrets:
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable mysecret_mypassword=password.
  # container-registry-secret:
  # password: 346ad110-0ab1-4341-8a24-653daa0264f4
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector:
    kubernetes.io/os: windows

tolerations: []

affinity: {}