// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NetCoreReflectionShim.CodeGen.Generators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Utils;
    using NetCoreReflectionShim.CodeGen;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class JsonReflectionClassTemplate : NetCoreReflectionShim.CodeGen.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Security.Claims;
using System.Threading.Tasks;
using Utils;
using CustomAttributeData = System.Reflection.CustomAttributeData;
");
            
            #line 22 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

    var type = this.Type;

            
            #line default
            #line hidden
            this.Write("\r\nnamespace CoreShim.Reflection.JsonTypes\r\n{\r\n");
            
            #line 28 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

    if (type.BaseType == typeof(object))
    {

            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 32 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name));
            
            #line default
            #line hidden
            this.Write("Json\r\n    {\r\n");
            
            #line 34 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 39 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name));
            
            #line default
            #line hidden
            this.Write("Json : ");
            
            #line 39 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.BaseType.Name));
            
            #line default
            #line hidden
            this.Write("Json\r\n    {\r\n");
            
            #line 41 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

    }

    foreach (var property in type.GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.DeclaredOnly))
    {
        var typeName = type.Name;
        var propertyName = property.Name;

        if (property.PropertyType.IsEnum)
        {

            
            #line default
            #line hidden
            this.Write("        public string ");
            
            #line 52 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("Enum { get; set; }\r\n");
            
            #line 53 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

        }
        else if (property.PropertyType == typeof(object))
        {

            
            #line default
            #line hidden
            this.Write("        public string ");
            
            #line 58 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("Object { get; set; }\r\n        public string ");
            
            #line 59 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("ObjectType { get; set; }\r\n");
            
            #line 60 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

        }
        else if (property.PropertyType.IsScalar())
        {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 65 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.GetShortName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 65 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 66 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

        }
        else if (property.PropertyType.IsGenericCollection())
        {
            var itemType = property.PropertyType.GetGenericArguments()[0];

            if (itemType.IsScalar())
            {

            
            #line default
            #line hidden
            this.Write("        public List<");
            
            #line 75 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemType.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 75 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 76 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

            }
            else
            {
                var args = ReflectMember(property, this.NoShim);

                if (args.JsonPropertyType != null)
                {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 85 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(args.JsonPropertyType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 85 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 86 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

                }
                else if (args.CacheResult)
                {
                    DebugUtils.Break();
                }
            }
        }
        else
        {
            var args = ReflectMember(property, this.NoShim);

            if (args.JsonPropertyType != null)
            {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 101 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(args.JsonPropertyType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 101 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 102 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

            }
            else if (args.CacheResult)
            {
                DebugUtils.Break();
            }
        }
    }

    foreach (var method in type.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance))
    {
        var typeName = type.Name;
        var methodName = method.Name;

        if (!method.IsPrivate)
        {
            var args = ReflectMember(method, this.NoShim);

            if (args.CacheResult)
            {
                if (args.JsonPropertyType != null)
                {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 125 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(args.JsonPropertyType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 125 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 126 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

                }
                else if (method.ReturnType.IsEnum)
                {

            
            #line default
            #line hidden
            this.Write("        public int ");
            
            #line 131 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("MemberEnum { get; set; }\r\n");
            
            #line 132 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

                }
                else if (method.ReturnType == typeof(object))
                {

            
            #line default
            #line hidden
            this.Write("        public string ");
            
            #line 137 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("MemberObject { get; set; }\r\n        public string ");
            
            #line 138 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("MemberObjectType { get; set; }\r\n");
            
            #line 139 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

                }
                else if (method.ReturnType.IsScalar())
                {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 144 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType.GetShortName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 144 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Member { get; set; }\r\n");
            
            #line 145 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

                }
                else if (method.ReturnType.IsGenericCollection())
                {
                    var itemType = method.ReturnType.GetGenericArguments()[0];

                    if (itemType.IsScalar())
                    {

            
            #line default
            #line hidden
            this.Write("        public List<");
            
            #line 154 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemType.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 154 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Member { get; set; }\r\n");
            
            #line 155 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

                    }
                    else
                    {
                        DebugUtils.Break();
                    }
                }
                else
                {
                    DebugUtils.Break();
                }
            }
        }
    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 172 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

    public ReflectMemberEventArgs ReflectMember(System.Reflection.MemberInfo memberInfo, bool noShim)
    {
        var args = new ReflectMemberEventArgs(memberInfo, ReflectKind.JsonTypes, noShim);

        ReflectMemberCallback(this, args);

        return args;
    }

        
        #line default
        #line hidden
        
        #line 1 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\JsonReflectionClassTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::NetCoreReflectionShim.CodeGen.ReflectMemberEventHandler _ReflectMemberCallbackField;

/// <summary>
/// Access the ReflectMemberCallback parameter of the template.
/// </summary>
private global::NetCoreReflectionShim.CodeGen.ReflectMemberEventHandler ReflectMemberCallback
{
    get
    {
        return this._ReflectMemberCallbackField;
    }
}

private global::System.Type _TypeField;

/// <summary>
/// Access the Type parameter of the template.
/// </summary>
private global::System.Type Type
{
    get
    {
        return this._TypeField;
    }
}

private bool _NoShimField;

/// <summary>
/// Access the NoShim parameter of the template.
/// </summary>
private bool NoShim
{
    get
    {
        return this._NoShimField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool ReflectMemberCallbackValueAcquired = false;
if (this.Session.ContainsKey("ReflectMemberCallback"))
{
    this._ReflectMemberCallbackField = ((global::NetCoreReflectionShim.CodeGen.ReflectMemberEventHandler)(this.Session["ReflectMemberCallback"]));
    ReflectMemberCallbackValueAcquired = true;
}
if ((ReflectMemberCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ReflectMemberCallback");
    if ((data != null))
    {
        this._ReflectMemberCallbackField = ((global::NetCoreReflectionShim.CodeGen.ReflectMemberEventHandler)(data));
    }
}
bool TypeValueAcquired = false;
if (this.Session.ContainsKey("Type"))
{
    this._TypeField = ((global::System.Type)(this.Session["Type"]));
    TypeValueAcquired = true;
}
if ((TypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Type");
    if ((data != null))
    {
        this._TypeField = ((global::System.Type)(data));
    }
}
bool NoShimValueAcquired = false;
if (this.Session.ContainsKey("NoShim"))
{
    this._NoShimField = ((bool)(this.Session["NoShim"]));
    NoShimValueAcquired = true;
}
if ((NoShimValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("NoShim");
    if ((data != null))
    {
        this._NoShimField = ((bool)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
