// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NetCoreReflectionShim.CodeGen.Generators
{
    using System.Linq;
    using System.Text;
    using System.Reflection;
    using System.Collections.Generic;
    using Utils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ServerReflectionExtensionsClassTemplate : NetCoreReflectionShim.CodeGen.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using NetCoreReflectionShim.Service;\r\nusing System;\r\nusing System.Collections.Gen" +
                    "eric;\r\nusing System.Text;\r\nusing Utils;\r\nusing System.Linq;\r\nusing System.Reflec" +
                    "tion;\r\nusing System.IO;\r\nusing CoreShim.Reflection.JsonTypes;\r\nusing CodePlex.XP" +
                    "athParser;\r\nusing AbstraX.XPathBuilder;\r\n\r\nnamespace NetCoreReflectionShim\r\n{\r\n " +
                    "   public static class ReflectionExtensions\r\n    {\r\n        public static void H" +
                    "andleReflectionCommand(this INetCoreReflectionService service, StreamWriter outp" +
                    "utWriter, CommandPacket commandPacket)\r\n        {\r\n            switch (commandPa" +
                    "cket.Command)\r\n            {\r\n                case ServerCommands.LOAD_ASSEMBLY:" +
                    "\r\n                    {\r\n                        Assembly assembly;\r\n           " +
                    "             AssemblyJson assemblyJson;\r\n                        var location = " +
                    "(string)commandPacket.Arguments.SingleOrDefault(a => a.Key == \"Location\").Value;" +
                    "\r\n                        string assemblyName = null;\r\n\r\n                       " +
                    " if (location == null)\r\n                        {\r\n                            l" +
                    "ocation = (string)commandPacket.Arguments.Single(a => a.Key == \"Name\").Value;\r\n " +
                    "                           assemblyName = commandPacket.Arguments.GetAssemblyNam" +
                    "e();\r\n                        }\r\n\r\n                        if (service.CachedAss" +
                    "emblies.ContainsKey(location))\r\n                        {\r\n                     " +
                    "       assembly = service.CachedAssemblies[location];\r\n                        }" +
                    "\r\n                        else if (assemblyName != null)\r\n                      " +
                    "  {\r\n                            assembly = Assembly.Load(assemblyName);\r\n      " +
                    "                      service.CachedAssemblies.Add(location, assembly);\r\n       " +
                    "                 }\r\n                        else\r\n                        {\r\n   " +
                    "                         assembly = Assembly.LoadFrom(location);\r\n              " +
                    "              service.CachedAssemblies.Add(location, assembly);\r\n               " +
                    "         }\r\n\r\n                        assemblyJson = ClientMapper.Map(assembly)." +
                    "MapCachedValues(assembly);\r\n\r\n                        commandPacket = new Comman" +
                    "dPacket(commandPacket.Command, commandPacket.SentTimestamp, assemblyJson);\r\n    " +
                    "                    outputWriter.WriteJsonCommand(commandPacket);\r\n             " +
                    "       }\r\n\r\n                    break;\r\n\r\n");
            
            #line 67 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

    foreach (var member in this.ApiMembers.Where(m => !m.CacheResult))
    {
        var memberName = member.MemberInfo.Name;


            
            #line default
            #line hidden
            this.Write("                case ServerCommands.");
            
            #line 73 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.CommandMember));
            
            #line default
            #line hidden
            this.Write(":\r\n                    {\r\n                        Assembly assembly;\r\n           " +
                    "             (string locationOrName, int metadataToken, string[] args) = command" +
                    "Packet.Arguments.GetParts();\r\n");
            
            #line 77 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
 
        foreach (var line in member.ServerGetArgumentsCode.GetLines())
        {

            
            #line default
            #line hidden
            this.Write("                        ");
            
            #line 81 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 82 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write(@"
                        if (service.CachedAssemblies.ContainsKey(locationOrName))
                        {
                            assembly = service.CachedAssemblies[locationOrName];
                        }
                        else
                        {
                            assembly = Assembly.LoadFrom(locationOrName);
                            service.CachedAssemblies.Add(locationOrName, assembly);
                        }

");
            
            #line 96 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

        if (member.ParentTypeIsAssembly)
        {

            
            #line default
            #line hidden
            this.Write("                        if (metadataToken == 0)\r\n                        {\r\n     " +
                    "                       var module = assembly.GetModules().Single();\r\n");
            
            #line 103 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            if (member.IsCollectionReturn || member.IsArrayReturn)
            {

            
            #line default
            #line hidden
            this.Write("                            CommandPacket<List<");
            
            #line 107 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json>> returnCommandPacket;\r\n                            List<");
            
            #line 108 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json> ");
            
            #line 108 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 110 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
  
                if (member.ReturnElementType.Implements<ICustomAttributeProvider>())
                {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 114 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = assembly.");
            
            #line 114 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".AddTo(service.CachedTokenObjects).Select(");
            
            #line 114 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 114 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(").MapCachedValues(");
            
            #line 114 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 115 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

                }
                else if (member.NoCacheResult)
                {
                    if (member.MemberInfo.Name == "GetCustomAttributes")
                    {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 122 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = assembly.");
            
            #line 122 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".Select(");
            
            #line 122 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 122 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 123 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 128 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = assembly.");
            
            #line 128 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".Select(");
            
            #line 128 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 128 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 129 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

                    }

                }
                else
                {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 136 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = assembly.");
            
            #line 136 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".Select(");
            
            #line 136 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 136 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(").MapCachedValues(");
            
            #line 136 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 137 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

                }

            
            #line default
            #line hidden
            this.Write("\r\n                            returnCommandPacket = new CommandPacket<List<");
            
            #line 141 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json>>(commandPacket.Command, commandPacket.SentTimestamp, ");
            
            #line 141 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 142 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("                            CommandPacket<");
            
            #line 147 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json> returnCommandPacket;\r\n                            ");
            
            #line 148 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json ");
            
            #line 148 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                            ");
            
            #line 150 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = assembly.");
            
            #line 150 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                            returnCommandPacket = new CommandPacket<List<");
            
            #line 152 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json>>(commandPacket.Command, commandPacket.SentTimestamp, ");
            
            #line 152 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 153 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write(@"                            outputWriter.WriteJsonCommand(returnCommandPacket);
                        }
                        else
                        {
                            DebugUtils.Break();
                        }
                    }
");
            
            #line 163 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("                        if (metadataToken != 0)\r\n                        {\r\n     " +
                    "                       var module = assembly.GetModules().Single();\r\n");
            
            #line 171 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            if (member.IsCollectionReturn || member.IsArrayReturn)
            {

            
            #line default
            #line hidden
            this.Write("                            CommandPacket<List<");
            
            #line 175 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json>> returnCommandPacket;\r\n                            List<");
            
            #line 176 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json> ");
            
            #line 176 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n                            ");
            
            #line 177 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 177 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                            if (service.CachedTokenObjects.ContainsKey(metad" +
                    "ataToken))\r\n                            {\r\n                                ");
            
            #line 181 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 181 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentTypeName));
            
            #line default
            #line hidden
            this.Write(") service.CachedTokenObjects[metadataToken];\r\n                            }\r\n    " +
                    "                        else\r\n                            {\r\n                   " +
                    "             DebugUtils.Break();\r\n                                ");
            
            #line 186 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n                            }\r\n\r\n");
            
            #line 189 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
  
                if (member.ReturnElementType.Implements<ICustomAttributeProvider>())
                {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 193 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 193 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 193 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".AddTo(service.CachedTokenObjects).Select(");
            
            #line 193 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 193 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(").MapCachedValues(");
            
            #line 193 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 194 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
  
                }
                else if (member.NoCacheResult)
                {
                    if (member.MemberInfo.Name == "GetCustomAttributes")
                    {


            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 202 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 202 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 202 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".Select(");
            
            #line 202 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 202 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 203 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
  
                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 208 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 208 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 208 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".Select(");
            
            #line 208 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 208 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 209 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
  
                    }
                }
                else
                {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 215 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 215 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 215 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(".Select(");
            
            #line 215 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(" => ClientMapper.Map(");
            
            #line 215 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(").MapCachedValues(");
            
            #line 215 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnLambdaVariable));
            
            #line default
            #line hidden
            this.Write(")).ToList();\r\n");
            
            #line 216 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
  
                }

            
            #line default
            #line hidden
            this.Write("\r\n                            returnCommandPacket = new CommandPacket<List<");
            
            #line 220 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json>>(commandPacket.Command, commandPacket.SentTimestamp, ");
            
            #line 220 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 221 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("                            CommandPacket<");
            
            #line 226 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json> returnCommandPacket;\r\n                            ");
            
            #line 227 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json ");
            
            #line 227 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n                            ");
            
            #line 228 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 228 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                            if (service.CachedTokenObjects.ContainsKey(metad" +
                    "ataToken))\r\n                            {\r\n                                ");
            
            #line 232 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 232 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentTypeName));
            
            #line default
            #line hidden
            this.Write(") service.CachedTokenObjects[metadataToken];\r\n                            }\r\n    " +
                    "                        else\r\n                            {\r\n                   " +
                    "             DebugUtils.Break();\r\n                                ");
            
            #line 237 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n                            }\r\n\r\n                            ");
            
            #line 240 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 240 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 240 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                            returnCommandPacket = new CommandPacket<List<");
            
            #line 242 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnElementTypeText));
            
            #line default
            #line hidden
            this.Write("Json>>(commandPacket.Command, commandPacket.SentTimestamp, ");
            
            #line 242 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ReturnVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 243 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write(@"                            outputWriter.WriteJsonCommand(returnCommandPacket);
                        }
                        else
                        {
                            DebugUtils.Break();
                        }
                    }
");
            
            #line 253 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("\r\n                    break;\r\n");
            
            #line 258 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

    }


            
            #line default
            #line hidden
            this.Write("\r\n                default:\r\n                    DebugUtils.Break();\r\n            " +
                    "        break;\r\n            }\r\n        }\r\n");
            
            #line 268 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

    foreach (var grouping in this.ApiMembers.Where(m => m.CacheResult).GroupBy(m => m.ParentTypeName))
    {
        var firstMember = grouping.First();

            
            #line default
            #line hidden
            this.Write("\r\n        public static ");
            
            #line 274 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentTypeName));
            
            #line default
            #line hidden
            this.Write("Json MapCachedValues(this ");
            
            #line 274 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentTypeName));
            
            #line default
            #line hidden
            this.Write("Json ");
            
            #line 274 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentVariable));
            
            #line default
            #line hidden
            this.Write("Json, ");
            
            #line 274 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 274 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 276 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

        foreach (var member in grouping)
        {
            if (member.ReturnElementType.IsEnum)
            {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 282 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentVariable));
            
            #line default
            #line hidden
            this.Write("Json.");
            
            #line 282 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.MemberInfo.Name));
            
            #line default
            #line hidden
            this.Write("MemberEnum = ");
            
            #line 282 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 282 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 283 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 288 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentVariable));
            
            #line default
            #line hidden
            this.Write("Json.");
            
            #line 288 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.MemberInfo.Name));
            
            #line default
            #line hidden
            this.Write("Member = ");
            
            #line 288 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ParentVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 288 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ServerCallCode));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 289 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("\r\n            return ");
            
            #line 294 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstMember.ParentVariable));
            
            #line default
            #line hidden
            this.Write("Json;\r\n        }\r\n");
            
            #line 296 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write(@"
        public static IEnumerable<T> AddTo<T>(this IEnumerable<T> customAttributeProviders, Dictionary<int, ICustomAttributeProvider> tokenObjects) where T : ICustomAttributeProvider
        {
            customAttributeProviders.ForEach(p =>
            {
                switch (p)
                {
                    case MemberInfo memberInfo:

                        if (!tokenObjects.ContainsKey(memberInfo.MetadataToken))
                        {
                            tokenObjects.Add(memberInfo.MetadataToken, memberInfo);
                        }

                        break;

                    case ParameterInfo parameterInfo:
                        
                        if (!tokenObjects.ContainsKey(parameterInfo.MetadataToken))
                        {
                            tokenObjects.Add(parameterInfo.MetadataToken, parameterInfo);
                        }
                        
                        break;

                    default:
                        DebugUtils.Break();
                        break;
                }
            });

            return customAttributeProviders;
        }

    }
}
");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MC\CloudIDEaaS\root\NetCoreReflectionShim.CodeGen\Generators\ServerReflectionExtensionsClassTemplate.tt"

private global::System.EventHandler _DebugCallbackField;

/// <summary>
/// Access the DebugCallback parameter of the template.
/// </summary>
private global::System.EventHandler DebugCallback
{
    get
    {
        return this._DebugCallbackField;
    }
}

private global::System.Collections.Generic.List<ApiMember> _ApiMembersField;

/// <summary>
/// Access the ApiMembers parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<ApiMember> ApiMembers
{
    get
    {
        return this._ApiMembersField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool DebugCallbackValueAcquired = false;
if (this.Session.ContainsKey("DebugCallback"))
{
    this._DebugCallbackField = ((global::System.EventHandler)(this.Session["DebugCallback"]));
    DebugCallbackValueAcquired = true;
}
if ((DebugCallbackValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DebugCallback");
    if ((data != null))
    {
        this._DebugCallbackField = ((global::System.EventHandler)(data));
    }
}
bool ApiMembersValueAcquired = false;
if (this.Session.ContainsKey("ApiMembers"))
{
    this._ApiMembersField = ((global::System.Collections.Generic.List<ApiMember>)(this.Session["ApiMembers"]));
    ApiMembersValueAcquired = true;
}
if ((ApiMembersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ApiMembers");
    if ((data != null))
    {
        this._ApiMembersField = ((global::System.Collections.Generic.List<ApiMember>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
